(function(){function h(a){throw a;}var aa=void 0,k=!0,m=null,n=!1;function ba(a){return function(){return a}}var p,ca=this;function da(){}
function r(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function s(a){return a!==aa}function ea(a){return a!=m}function ga(a){return"array"==r(a)}function u(a){var b=r(a);return"array"==b||"object"==b&&"number"==typeof a.length}function v(a){return"string"==typeof a}function w(a){return"boolean"==typeof a}function ha(a){return"number"==typeof a}function ja(a){return"function"==r(a)}function ka(a){var b=typeof a;return"object"==b&&a!=m||"function"==b}
var ma="closure_uid_"+(1E9*Math.random()>>>0),na=0;function x(a,b){var c=a.split("."),d=ca;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&s(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}function oa(a,b){function c(){}c.prototype=b.prototype;a.Ya=b.prototype;a.prototype=new c;a.prototype.constructor=a};var y=Array.prototype,pa=y.indexOf?function(a,b,c){return y.indexOf.call(a,b,c)}:function(a,b,c){c=c==m?0:0>c?Math.max(0,a.length+c):c;if(v(a))return!v(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ra=y.forEach?function(a,b,c){y.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=v(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},sa=y.filter?function(a,b,c){return y.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=v(a)?
a.split(""):a,j=0;j<d;j++)if(j in g){var l=g[j];b.call(c,l,j,a)&&(e[f++]=l)}return e},ta=y.map?function(a,b,c){return y.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=v(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};function ua(a,b){var c=pa(a,b);0<=c&&y.splice.call(a,c,1)}function va(a){return y.concat.apply(y,arguments)}function wa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function xa(a,b,c){return 2>=arguments.length?y.slice.call(a,b):y.slice.call(a,b,c)}function za(a,b,c){if(!u(a)||!u(b)||a.length!=b.length)return n;var d=a.length;c=c||Aa;for(var e=0;e<d;e++)if(!c(a[e],b[e]))return n;return k}function Ba(a,b){return a>b?1:a<b?-1:0}function Aa(a,b){return a===b}function Ca(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var d=[],e=0;e<arguments.length;e++){var f=arguments[e];if(c>=f.length)return b;d.push(f[c])}b.push(d)}};var z="StopIteration"in ca?ca.StopIteration:Error("StopIteration");function B(){}B.prototype.next=function(){h(z)};B.prototype.u=function(){return this};function Da(a){if(a instanceof B)return a;if("function"==typeof a.u)return a.u(n);if(u(a)){var b=0,c=new B;c.next=function(){for(;;){b>=a.length&&h(z);if(b in a)return a[b++];b++}};return c}h(Error("Not implemented"))}
function D(a,b,c){if(u(a))try{ra(a,b,c)}catch(d){d!==z&&h(d)}else{a=Da(a);try{for(;;)b.call(c,a.next(),aa,a)}catch(e){e!==z&&h(e)}}}function E(a,b,c){var d=Da(a);a=new B;a.next=function(){for(;;){var a=d.next();return b.call(c,a,aa,d)}};return a}function Ea(a,b,c){var d=c;D(a,function(a){d=b.call(aa,d,a)});return d}function Fa(a){var b=arguments,c=b.length,d=0,e=new B;e.next=function(){try{return d>=c&&h(z),Da(b[d]).next()}catch(a){return(a!==z||d>=c)&&h(a),d++,this.next()}};return e}
function Ga(a){if(u(a))return wa(a);a=Da(a);var b=[];D(a,function(a){b.push(a)});return b}function La(a,b){try{return Da(a).next()}catch(c){return c!=z&&h(c),b}};function Ma(){}Ma.ga=function(){return Ma.ia?Ma.ia:Ma.ia=new Ma};Ma.prototype.za=0;Ma.ga();var Na={};function Oa(a){if(!u(a))return n;for(var b=0,c=a.length;b<c;b++)if(window.isNaN(a[b]))return n;return k}x("jsnx.utils.is_list_of_ints",Oa);x("jsnx.utils.cumulative_sum",function(a){var b=0;return E(a,function(a){return b+=a})});x("jsnx.utils.generate_unique_node",function(){return":"+(Ma.ga().za++).toString(36)});function F(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Qa(a,b,c){var d={},e;for(e in a)d[e]=b.call(c,a[e],e,a);return d}function G(a){var b=0,c;for(c in a)b++;return b}function Ta(a){for(var b in a)return b}function Ua(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function H(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function Va(a){for(var b in a)delete a[b]}function I(a,b){b in a&&delete a[b]}function J(a,b,c){return b in a?a[b]:c}
function Wa(a){var b={},c;for(c in a)b[c]=a[c];return b}var Xa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function K(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Xa.length;f++)c=Xa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}}
function Ya(a){var b=arguments.length;if(1==b&&ga(arguments[0]))return Ya.apply(m,arguments[0]);b%2&&h(Error("Uneven number of arguments"));for(var c={},d=0;d<b;d+=2)c[arguments[d]]=arguments[d+1];return c};function Za(a){if("function"==typeof a.A)return a.A();if(v(a))return a.split("");if(u(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Ua(a)};function $a(a,b){this.f={};this.j=[];var c=arguments.length;if(1<c){c%2&&h(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.$(a)}p=$a.prototype;p.v=0;p.W=0;p.e=function(){return this.v};p.A=function(){ab(this);for(var a=[],b=0;b<this.j.length;b++)a.push(this.f[this.j[b]]);return a};p.O=function(){return 0==this.v};p.clear=function(){this.f={};this.W=this.v=this.j.length=0};
p.remove=function(a){return Object.prototype.hasOwnProperty.call(this.f,a)?(delete this.f[a],this.v--,this.W++,this.j.length>2*this.v&&ab(this),k):n};function ab(a){if(a.v!=a.j.length){for(var b=0,c=0;b<a.j.length;){var d=a.j[b];Object.prototype.hasOwnProperty.call(a.f,d)&&(a.j[c++]=d);b++}a.j.length=c}if(a.v!=a.j.length){for(var e={},c=b=0;b<a.j.length;)d=a.j[b],Object.prototype.hasOwnProperty.call(e,d)||(a.j[c++]=d,e[d]=1),b++;a.j.length=c}}
p.set=function(a,b){Object.prototype.hasOwnProperty.call(this.f,a)||(this.v++,this.j.push(a),this.W++);this.f[a]=b};p.$=function(a){var b;a instanceof $a?(ab(a),b=a.j.concat(),a=a.A()):(b=H(a),a=Ua(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};p.X=function(){return new $a(this)};
p.u=function(a){ab(this);var b=0,c=this.j,d=this.f,e=this.W,f=this,g=new B;g.next=function(){for(;;){e!=f.W&&h(Error("The map has changed since the iterator was created"));b>=c.length&&h(z);var g=c[b++];return a?g:d[g]}};return g};function L(a){this.f=new $a;a&&this.$(a)}function bb(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[ma]||(a[ma]=++na)):b.substr(0,1)+a}p=L.prototype;p.e=function(){return this.f.e()};p.add=function(a){this.f.set(bb(a),a)};p.$=function(a){a=Za(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])};p.remove=function(a){return this.f.remove(bb(a))};p.clear=function(){this.f.clear()};p.O=function(){return this.f.O()};
p.contains=function(a){a=bb(a);return Object.prototype.hasOwnProperty.call(this.f.f,a)};function cb(a,b){for(var c=new L,d=Za(b),e=0;e<d.length;e++){var f=d[e];a.contains(f)&&c.add(f)}return c}function db(a,b){for(var c=a.X(),d=Za(b),e=d.length,f=0;f<e;f++)c.remove(d[f]);return c}p.A=function(){return this.f.A()};p.X=function(){return new L(this)};p.u=function(){return this.f.u(n)};function eb(a){if(a!=m)try{a.clear()}catch(b){h(Error("Input graph is not a jsnx graph type"))}else a=new Na.Fa;return a}
function fb(a,b,c){var d;if(a.hasOwnProperty("adj"))try{return d=mb(a.adj,b,a.i()),"graph"in a&&"object"===r(a.graph)&&(d.graph=Wa(a.graph)),"node"in a&&"object"===r(a.node)&&(d.node=Qa(a.node,function(a){return Wa(a)})),d}catch(e){h(Error("Input is not a correct jsnx graph"))}if("object"===r(a))try{return mb(a,b,c)}catch(f){try{var g=eb(b);g.h(a);if(g.i()&&!g.c()){var j={};F(a,function(a,b){ra(a,function(a){a in j||g.g(b,a)});j[b]=1})}else{var l=[];F(a,function(a,b){ra(a,function(a){l.push([b,a])})});
g.a(l)}return g}catch(A){h(Error("Input is not known type."))}}if(u(a))try{var q=eb(b);q.a(a);return q}catch(t){h(Error("Input is not valid edge list"))}}x("jsnx.to_networkx_graph",fb);x("jsnx.convert_to_undirected",Na.La);x("jsnx.convert_to_undirected",Na.Ka);x("jsnx.to_dict_of_lists",Na.Za);
function mb(a,b,c){var d=eb(b),e,f;d.h(a);c?d.c()?(d.i()?(e=[],F(a,function(a,b){u(a)&&h(Error());F(a,function(a,c){F(a,function(a,d){e.push([b,c,d,a])})})})):(e=[],F(a,function(a,b){u(a)&&h(Error());F(a,function(a,c){F(a,function(a){e.push([b,c,a])})})})),d.a(e)):d.i()?(f=new L,F(a,function(a,b){u(a)&&h(Error());F(a,function(a,c){f.contains([b,c].toString())||(e=[],F(a,function(a,d){e.push([b,c,d,a])}),d.a(e),f.add([c,b].toString()))})})):(f=new L,F(a,function(a,b){u(a)&&h(Error());F(a,function(a,
c){f.contains([b,c].toString())||(e=[],F(a,function(a){e.push([b,c,a])}),d.a(e),f.add([c,b].toString()))})})):d.i()&&!d.c()?(f=new L,F(a,function(a,b){u(a)&&h(Error());F(a,function(a,c){f.contains([b,c].toString())||(d.g(b,c,a),f.add([c,b].toString()))})})):(e=[],F(a,function(a,b){u(a)&&h(Error());F(a,function(a,c){e.push([b,c,a])})}),d.a(e));return d};function nb(a){this.name="JSNetworkXException";this.message=a}nb.prototype=Error();nb.prototype.constructor=nb;x("jsnx.JSNetworkXException",nb);function M(a){nb.call(this,a);this.name="JSNetworkXError"}oa(M,nb);x("jsnx.JSNetworkXError",M);function ob(a){nb.call(this,a);this.name="JSNetworkXPointlessConcept"}oa(ob,nb);x("jsnx.JSNetworkXPointlessConcept",ob);function pb(a){nb.call(this,a);this.name="JSNetworkXAlgorithmError"}oa(pb,nb);x("jsnx.JSNetworkXAlgorithmError",pb);
function qb(a){pb.call(this,a);this.name="JSNetworkXUnfeasible"}oa(qb,pb);x("jsnx.JSNetworkXUnfeasible",qb);function rb(a){qb.call(this,a);this.name="JSNetworkXNoPath"}oa(rb,qb);x("jsnx.JSNetworkXNoPath",rb);function sb(a){pb.call(this,a);this.name="JSNetworkXUnbounded"}oa(sb,pb);x("jsnx.JSNetworkXUnbounded",sb);function tb(a){return Ea(ub(a),function(a,c){a[c[0]]=c[1];return a},{})}function vb(a){return a instanceof B||ja(a.u)}function wb(a){if(v(a)||u(a)||"length"in a)return a.length;if(xb(a))return G(a);h(new TypeError)}function O(a,b,c,d){w(c)&&(d=c,c=m);if(d){var e=b;b=function(a){e.apply(this,a)}}vb(a)?D(a,b,c):u(a)||v(a)?ra(a,b,c):ka(a)&&O(H(a),b,c)}x("jsnx.forEach",O);function P(a,b,c){if(u(a))return ta(a,b,c);if(vb(a))return E(a,b,c);if(ka(a))return Qa(a,b,c);h(new TypeError)}
function yb(){var a=arguments,b=a[0];if(u(b))return Ca.apply(m,a);if(vb(b)){var b=new B,c=a.length;b.next=function(){for(var b=[],e=0;e<c;e++)b.push(a[e].next());return b};return b}if(ka(b))return Ca.apply(m,ta(a,H));h(new TypeError)}
function zb(a,b,c){if(0===arguments.length)return[];1===arguments.length?(b=a,a=0,c=1):2===arguments.length?c=1:3===arguments.length&&0===arguments[2]&&h("range() step argument must not be zero");var d=new B,e=0>c,f=a,g;d.next=function(){(e&&f<=b||!e&&f>=b)&&h(z);g=f;f+=c;return g};return d}
function Ab(a){var b=Q(a),c=b.length;if(2>c)return new B;var d=Q(zb(2));a=new B;a.next=function(){var a=ta(d,function(a){return b[a]});this.next=function(){var a=n,e;for(e=2;e--;)if(d[e]!=e+c-2){a=k;break}a||h(z);d[e]+=1;for(a=e+1;2>a;a++)d[a]=d[a-1]+1;return ta(d,function(a){return b[a]})};return a};return a}
function Bb(a){var b=Q(a),c=b.length,d=ha(2)?2:c;if(d>c)return new B;var e=Q(zb(c)),f=Q(zb(c,c-d,-1));a=new B;var g=new B,j,l=k;a.next=function(){this.next=j.next;return ta(e.slice(0,d),function(a){return b[a]})};g.next=function(){return l};j=S(g,function(a){a||h(z);l=n;return zb(d-1,-1,-1)},function(a){if(!l)if(f[a]-=1,0===f[a])e.splice.apply(e,[a,e.length].concat(e.slice(a+1).concat([e[a]]))),f[a]=c-a;else{var g=f[a],j=e[a];e[a]=e[e.length-g];e[e.length-g]=j;l=k;return ub([ta(e.slice(0,d),function(a){return b[a]})])}},
function(a){return a});return a}function Db(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)!s(a[c])||"object"!==r(a[c])?a[c]=T(d[c]):"object"===r(a[c])&&"object"===r(d)&&Db(a[c],d[c]);for(var f=0;f<Xa.length;f++)c=Xa[f],Object.prototype.hasOwnProperty.call(d,c)&&(!s(a[c])||"object"!==r(a[c])?a[c]=T(d[c]):"object"===r(a[c])&&"object"===r(d)&&Db(a[c],d[c]))}}function Q(a){if(u(a))return wa(a);if(vb(a))return Ga(a);if(ka(a))return H(a);h(new TypeError)}x("jsnx.toArray",Q);
function Eb(a){var b=[];F(a,function(a,d){b.push([d,a])});return b}function U(a){var b=new B,c=Da(H(a));b.next=function(){var b=c.next();return[b,a[b]]};return b}function ub(a){"object"===r(a)&&(!u(a)&&!vb(a))&&(a=H(a));return Da(a)}
function S(a){var b=new B,c=xa(arguments,1);if(0===c.length)return a;try{a=Da(a)}catch(d){return b.next=function(){"Not implemented"===d.message&&h(new TypeError)},b}var e=m;b.next=function(){var d,g;try{for(;!s(d);)d=e.next()}catch(j){for(;!s(g)||!s(d);)g=a.next(),d=c[0](g);if(vb(d))return e=S.apply(m,va([d],xa(c,1))),b.next();e=m}return d};return b}x("jsnx.sentinelIterator",function(a,b){var c=new B;c.next=function(){return La(a,b)};return c});
function xb(a){var b=Object.prototype.hasOwnProperty;if(!a||"object"!==r(a)||a.nodeType||a==a.window)return n;try{if(a.constructor&&!b.call(a,"constructor")&&!b.call(a.constructor.prototype,"isPrototypeOf"))return n}catch(c){return n}for(var d in a);return d===aa||b.call(a,d)}
function T(a,b){b=b||[];var c=r(a);if("object"==c&&xb(a)||"array"==c){var d;d=b;var e;a:{e=function(b){return a===b[0]};for(var f=d.length,g=v(d)?d.split(""):d,j=0;j<f;j++)if(j in g&&e.call(aa,g[j])){e=j;break a}e=-1}d=0>e?m:v(d)?d.charAt(e):d[e];if(d!==m)return d[1];if(a.X)return d=[a,a.X()],b.push(d),d[1];c="array"==c?[]:{};d=[a,c];b.push(d);for(var l in a)c[l]=T(a[l],b);return c}return a}
function Fb(a){function b(){}var c={},d;b.prototype=a.constructor.prototype;for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);c=T(c);a=new b;for(d in c)a[d]=c[d];return a};function Gb(a){var b=[];Hb(new Ib,a,b);return b.join("")}function Ib(){this.Z=aa}
function Hb(a,b,c){switch(typeof b){case "string":Jb(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==m){c.push("null");break}if(ga(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],Hb(a,a.Z?a.Z.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),Jb(f,c),c.push(":"),
Hb(a,a.Z?a.Z.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:h(Error("Unknown type: "+typeof b))}}var Kb={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},Lb=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function Jb(a,b){b.push('"',a.replace(Lb,function(a){if(a in Kb)return Kb[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return Kb[a]=e+b.toString(16)}),'"')};var V={Ta:function(a){return Math.floor(Math.random()*a)},ab:function(a,b){return a+Math.random()*(b-a)},Ja:function(a,b,c){return Math.min(Math.max(a,b),c)},ya:function(a,b){var c=a%b;return 0>c*b?c+b:c},Qa:function(a,b,c){return a+c*(b-a)},Sa:function(a,b,c){return Math.abs(a-b)<=(c||1E-6)},da:function(a){return V.ya(a,360)},la:function(a){return a*Math.PI/180},Ea:function(a){return 180*a/Math.PI},Ha:function(a,b){return b*Math.cos(V.la(a))},Ia:function(a,b){return b*Math.sin(V.la(a))},fa:function(a,
b,c,d){return V.da(V.Ea(Math.atan2(d-b,c-a)))},Ga:function(a,b){var c=V.da(b)-V.da(a);180<c?c-=360:-180>=c&&(c=360+c);return c},Wa:function(a){return 0==a?0:0>a?-1:1},Ra:function(a,b,c,d){c=c||function(a,b){return a==b};d=d||function(b){return a[b]};for(var e=a.length,f=b.length,g=[],j=0;j<e+1;j++)g[j]=[],g[j][0]=0;for(var l=0;l<f+1;l++)g[0][l]=0;for(j=1;j<=e;j++)for(l=1;l<=e;l++)g[j][l]=c(a[j-1],b[l-1])?g[j-1][l-1]+1:Math.max(g[j-1][l],g[j][l-1]);for(var A=[],j=e,l=f;0<j&&0<l;)c(a[j-1],b[l-1])?(A.unshift(d(j-
1,l-1)),j--,l--):g[j-1][l]>g[j][l-1]?j--:l--;return A},o:function(a){var b;b=arguments;var c=function(a,b){return a+b};if(b.reduce)b=b.reduce(c,0);else{var d=0;ra(b,function(a){d=c.call(aa,d,a)});b=d}return b},sa:function(a){return V.o.apply(m,arguments)/arguments.length},Xa:function(a){var b=arguments.length;if(2>b)return 0;var c=V.sa.apply(m,arguments),b=V.o.apply(m,ta(arguments,function(a){return Math.pow(a-c,2)}))/(b-1);return Math.sqrt(b)},Pa:function(a){return isFinite(a)&&0==a%1},Oa:function(a){return isFinite(a)&&
!isNaN(a)},Va:function(a,b){return Math.floor(a+(b||2E-15))},Ua:function(a,b){return Math.ceil(a-(b||2E-15))}};function X(a,b){if(!(this instanceof X))return new X(a,b);this.graph={};this.node={};this.adj={};a!=m&&fb(a,this);K(this.graph,b||{});this.edge=this.adj}x("jsnx.classes.Graph",X);x("jsnx.Graph",X);X.__name__="Graph";X.prototype.va=m;X.prototype.graph=X.prototype.va;X.prototype.ba=m;X.prototype.node=X.prototype.ba;X.prototype.qa=m;X.prototype.adj=X.prototype.qa;X.prototype.ta=m;X.prototype.edge=X.prototype.ta;
X.prototype.name=function(a){if(s(a))this.graph.name=a.toString();else return this.graph.name||""};X.prototype.name=X.prototype.name;X.prototype.toString=function(){return this.name()};X.prototype.toString=X.prototype.toString;X.prototype.u=function(){return ub(this.adj)};X.prototype.__iterator__=X.prototype.u;X.prototype.l=function(a){a in this.adj||h({name:"KeyError",message:"Graph does not contain node "+a+"."});return this.adj[a]};X.prototype.get_node=X.prototype.l;
X.prototype.H=function(a,b){b!=m||(b={});"object"!==r(b)&&h(new M("The attr_dict argument must be an object."));a in this.adj?K(this.node[a],b||{}):(this.adj[a]={},this.node[a]=b||{})};X.prototype.add_node=X.prototype.H;X.prototype.h=function(a,b){var c,d,e,f,g;b=b||{};O(a,function(a){c=!(a in this.adj);ga(a)?(d=a[0],e=a[1],d in this.adj?(g=this.node[d],K(g,b,e)):(this.adj[d]={},f=Wa(b),K(f,e),this.node[d]=f)):c?(this.adj[a]={},this.node[a]=Wa(b)):K(this.node[a],b)},this)};
X.prototype.add_nodes_from=X.prototype.h;X.prototype.K=function(a){var b=this.adj,c;a in this.node||h(new M("The node "+a+" is not in the graph"));c=H(b[a]);I(this.node,a);ra(c,function(c){I(b[c],a)});I(b,a)};X.prototype.remove_node=X.prototype.K;X.prototype.T=function(a){var b=this.adj;O(a,function(a){try{I(this.node,a),F(b[a],function(d,f){I(b[f],a)}),I(b,a)}catch(d){}},this)};X.prototype.remove_nodes_from=X.prototype.T;X.prototype.D=function(a){return a?U(this.node):ub(H(this.adj))};
X.prototype.nodes_iter=X.prototype.D;X.prototype.nodes=function(a){return Ga(this.D(a))};X.prototype.nodes=X.prototype.nodes;X.prototype.R=function(){return G(this.adj)};X.prototype.number_of_nodes=X.prototype.R;X.prototype.w=function(){return G(this.adj)};X.prototype.order=X.prototype.w;X.prototype.k=function(a){return!ga(a)&&a in this.adj};X.prototype.has_node=X.prototype.k;
X.prototype.g=function(a,b,c){c=c||{};"object"!==r(c)&&h(new M("The attr_dict argument must be an object."));a in this.adj||(this.adj[a]={},this.node[a]={});b in this.adj||(this.adj[b]={},this.node[b]={});var d=J(this.adj[a],b,{});K(d,c);this.adj[a][b]=d;this.adj[b][a]=d};X.prototype.add_edge=X.prototype.g;
X.prototype.a=function(a,b){b=b||{};"object"!==r(b)&&h(new M("The attr_dict argument must be an object."));O(a,function(a){var d=wb(a),e,f,g;3===d?(e=a[0],f=a[1],g=a[2]):2===d?(e=a[0],f=a[1],g={}):h(new M("Edge tuple "+a.toString()+" must be a 2-tuple or 3-tuple."));e in this.adj||(this.adj[e]={},this.node[e]={});f in this.adj||(this.adj[f]={},this.node[f]={});a=J(this.adj[e],f,{});K(a,b,g);this.adj[e][f]=a;this.adj[f][e]=a},this)};X.prototype.add_edges_from=X.prototype.a;
X.prototype.pa=function(a,b,c){c=c||{};v(b)||(c=b,b="weight");this.a(P(a,function(a){var c={};c[b]=a[2];s(c[b])||h(new TypeError("Values must consist of three elements: "+Gb(a)));return[a[0],a[1],c]}),c)};X.prototype.add_weighted_edges_from=X.prototype.pa;X.prototype.s=function(a,b){try{I(this.adj[a],b),a!=b&&I(this.adj[b],a)}catch(c){c instanceof TypeError&&h(new M("The edge "+a+"-"+b+" is not in the graph")),h(c)}};X.prototype.remove_edge=X.prototype.s;
X.prototype.z=function(a){O(a,function(a){var c=a[0];a=a[1];c in this.adj&&a in this.adj[c]&&(I(this.adj[c],a),c!=a&&I(this.adj[a],c))},this)};X.prototype.remove_edges_from=X.prototype.z;X.prototype.B=function(a,b){return a in this.adj&&b in this.adj[a]};X.prototype.has_edge=X.prototype.B;X.prototype.I=function(a){a in this.adj||h(new M("The node "+a+" is not in the graph."));return Q(this.adj[a])};X.prototype.neighbors=X.prototype.I;
X.prototype.aa=function(a){a in this.adj||h(new M("The node "+a+" is not in the graph."));return ub(this.adj[a])};X.prototype.neighbors_iter=X.prototype.aa;X.prototype.q=function(a,b){return Q(this.d(a,b))};X.prototype.edges=X.prototype.q;
X.prototype.d=function(a,b){w(a)&&(b=a,a=m);var c={},d,e;d=a!=m?P(this.b(a),function(a){return[a,this.adj[a]]},this):U(this.adj);return b?S(d,function(a){e=a[0];var b=new B,d=U(a[1]);b.next=function(){try{return d.next()}catch(a){a===z&&(c[e]=1),h(a)}};return b},function(a){if(!(a[0]in c))return[e,a[0],a[1]]}):S(d,function(a){e=a[0];var b=new B,d=ub(a[1]);b.next=function(){try{return d.next()}catch(a){a===z&&(c[e]=1),h(a)}};return b},function(a){if(!(a in c))return[e,a]})};
X.prototype.edges_iter=X.prototype.d;X.prototype.L=function(a,b,c){s(c)||(c=m);return a in this.adj?J(this.adj[a],b,c):c};X.prototype.get_edge_data=X.prototype.L;X.prototype.ra=function(){return Q(P(this.p(),function(a){return H(a[1])}))};X.prototype.adjacency_list=X.prototype.ra;X.prototype.p=function(){return U(this.adj)};X.prototype.adjacency_iter=X.prototype.p;X.prototype.m=function(a,b){return this.k(a)?this.n(a,b).next()[1]:tb(Ga(this.n(a,b)))};X.prototype.degree=X.prototype.m;
X.prototype.n=function(a,b){var c;c=a!=m?P(this.b(a),function(a){return[a,this.adj[a]]},this):U(this.adj);return b?P(c,function(a){var c=a[0];a=a[1];var f=0,g;for(g in a)f+=+J(a[g],b,1);f+=+(c in a&&J(a[c],b,1));return[c,f]}):P(c,function(a){return[a[0],G(a[1])+ +(a[0]in a[1])]})};X.prototype.degree_iter=X.prototype.n;X.prototype.clear=function(){this.name("");Va(this.adj);Va(this.node);Va(this.graph)};X.prototype.clear=X.prototype.clear;X.prototype.copy=function(){return Fb(this)};
X.prototype.copy=X.prototype.copy;X.prototype.i=ba(n);X.prototype.is_multigraph=X.prototype.i;X.prototype.c=ba(n);X.prototype.is_directed=X.prototype.c;X.prototype.F=function(){var a=new Y;a.name(this.name());a.h(this);a.a(function(){var a;return S(this.p(),function(c){a=c[0];return U(c[1])},function(c){return[a,c[0],T(c[1])]})}.call(this));a.graph=T(this.graph);a.node=T(this.node);return a};X.prototype.to_directed=X.prototype.F;X.prototype.V=function(){return Fb(this)};
X.prototype.to_undirected=X.prototype.V;X.prototype.t=function(a){a=this.b(a);var b=new this.constructor,c=b.adj,d=this.adj;O(a,function(a){var b={};c[a]=b;F(d[a],function(d,j){j in c&&(b[j]=d,c[j][a]=d)})});O(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};X.prototype.subgraph=X.prototype.t;X.prototype.Aa=function(){return ta(sa(Eb(this.adj),function(a){return a[0]in a[1]}),function(a){return a[0]})};X.prototype.nodes_with_selfloops=X.prototype.Aa;
X.prototype.U=function(a){return a?ta(sa(Eb(this.adj),function(a){return a[0]in a[1]}),function(a){var c=a[0];return[c,c,a[1][c]]}):ta(sa(Eb(this.adj),function(a){return a[0]in a[1]}),function(a){return[a[0],a[0]]})};X.prototype.selfloop_edges=X.prototype.U;X.prototype.Ba=function(){return this.U().length};X.prototype.number_of_selfloops=X.prototype.Ba;X.prototype.size=function(a){var b=V.o.apply(m,Ua(this.m(m,a)))/2;return a!=m?b:Math.floor(b)};X.prototype.size=X.prototype.size;
X.prototype.J=function(a,b){return a==m?Math.floor(this.size()):b in this.adj[a]?1:0};X.prototype.number_of_edges=X.prototype.J;X.prototype.oa=function(a,b){var c=Q(a),d=c[0],c=P(xa(c,1),function(a){return[d,a]});this.a(c,b)};X.prototype.add_star=X.prototype.oa;X.prototype.na=function(a,b){var c=Q(a),c=Ca(xa(c,0,c.length-1),xa(c,1));this.a(c,b)};X.prototype.add_path=X.prototype.na;X.prototype.ma=function(a,b){var c=Q(a),c=Ca(c,va(xa(c,1),[c[0]]));this.a(c,b)};X.prototype.add_cycle=X.prototype.ma;
X.prototype.b=function(a){if(a!=m)if(this.k(a))a=ub([a.toString()]);else{var b=this.adj,c=new B,d=S(a,function(a){if(a in b)return a.toString()});c.next=function(){try{return d.next()}catch(a){a instanceof TypeError&&h(new M("nbunch is not a node or a sequence of nodes")),h(a)}};a=c}else a=ub(this.adj);return a};X.prototype.nbunch_iter=X.prototype.b;function Y(a,b){if(!(this instanceof Y))return new Y(a,b);this.graph={};this.node={};this.adj={};this.pred={};this.succ=this.adj;a!=m&&fb(a,this);K(this.graph,b||{});this.edge=this.adj}x("jsnx.classes.DiGraph",Y);x("jsnx.DiGraph",Y);oa(Y,X);Y.__name__="DiGraph";Y.prototype.H=function(a,b){b!=m||(b={});"object"!==r(b)&&h(new M("The attr_dict argument must be an object."));a in this.succ?K(this.node[a],b):(this.succ[a]={},this.pred[a]={},this.node[a]=b)};Y.prototype.add_node=Y.prototype.H;
Y.prototype.h=function(a,b){var c,d,e,f,g;b=b||{};O(ub(a),function(a){c=!(a in this.succ);ga(a)?(d=a[0],e=a[1],d in this.succ?(g=this.node[d],K(g,b,e)):(this.succ[d]={},this.pred[d]={},f=Wa(b),K(f,e),this.node[d]=f)):c?(this.succ[a]={},this.pred[a]={},this.node[a]=Wa(b)):K(this.node[a],b)},this)};Y.prototype.add_nodes_from=Y.prototype.h;
Y.prototype.K=function(a){a in this.node||h(new M("The node "+a+" is not in the graph"));var b=this.succ[a];I(this.node,a);F(b,function(b,d){I(this.pred[d],a)},this);I(this.succ,a);F(this.pred[a],function(b,d){I(this.succ[d],a)},this);I(this.pred,a)};Y.prototype.remove_node=Y.prototype.K;
Y.prototype.T=function(a){var b;O(a,function(a){a in this.succ&&(b=this.succ[a],I(this.node,a),F(b,function(b,e){I(this.pred[e],a)},this),I(this.succ,a),F(this.pred[a],function(b,e){I(this.succ[e],a)},this),I(this.pred,a))},this)};Y.prototype.remove_nodes_from=Y.prototype.T;
Y.prototype.g=function(a,b,c){c=c||{};"object"!==r(c)&&h(new M("The attr_dict argument must be an object."));a in this.succ||(this.succ[a]={},this.pred[a]={},this.node[a]={});b in this.succ||(this.succ[b]={},this.pred[b]={},this.node[b]={});var d=J(this.adj[a],b,{});K(d,c);this.succ[a][b]=d;this.pred[b][a]=d};Y.prototype.add_edge=Y.prototype.g;
Y.prototype.a=function(a,b){b=b||{};"object"!==r(b)&&h(new M("The attr_dict argument must be an object."));O(a,function(a){var d=wb(a),e,f,g;3===d?(e=a[0],f=a[1],g=a[2]):2===d?(e=a[0],f=a[1],g={}):h(new M("Edge tuple "+a.toString()+" must be a 2-tuple or 3-tuple."));e in this.succ||(this.succ[e]={},this.pred[e]={},this.node[e]={});f in this.succ||(this.succ[f]={},this.pred[f]={},this.node[f]={});a=J(this.adj[e],f,{});K(a,b,g);this.succ[e][f]=a;this.pred[f][e]=a},this)};
Y.prototype.add_edges_from=Y.prototype.a;Y.prototype.s=function(a,b){try{I(this.succ[a],b),I(this.pred[b],a)}catch(c){c instanceof TypeError&&h(new M("The edge "+a+"-"+b+" is not in the graph")),h(c)}};Y.prototype.remove_edge=Y.prototype.s;Y.prototype.z=function(a){O(a,function(a){var c=a[0];a=a[1];c in this.succ&&a in this.succ[c]&&(I(this.succ[c],a),I(this.pred[a],c))},this)};Y.prototype.remove_edges_from=Y.prototype.z;Y.prototype.xa=function(a,b){return a in this.succ&&b in this.succ[a]};
Y.prototype.has_successor=Y.prototype.xa;Y.prototype.wa=function(a,b){return a in this.pred&&b in this.pred[a]};Y.prototype.has_predecessor=Y.prototype.wa;Y.prototype.ka=function(a){a in this.succ||h(new M("The node "+a+" is not in the digraph."));return ub(this.succ[a])};Y.prototype.successors_iter=Y.prototype.ka;Y.prototype.Da=function(a){a in this.pred||h(new M("The node "+a+" is not in the digraph."));return ub(this.pred[a])};Y.prototype.predecessors_iter=Y.prototype.Da;
Y.prototype.ea=function(a){a in this.succ||h(new M("The node "+a+" is not in the digraph."));return Q(this.succ[a])};Y.prototype.successors=Y.prototype.ea;Y.prototype.Ca=function(a){a in this.succ||h(new M("The node "+a+" is not in the digraph."));return Q(this.pred[a])};Y.prototype.predecessors=Y.prototype.Ca;Y.prototype.I=Y.prototype.ea;Y.prototype.neighbors=Y.prototype.I;Y.prototype.aa=Y.prototype.ka;Y.prototype.neighbors_iter=Y.prototype.aa;
Y.prototype.d=function(a,b){w(a)&&(b=a,a=m);var c,d,e;c=a!=m?P(this.b(a),function(a){return[a,this.adj[a]]},this):Eb(this.adj);return b?S(c,function(a){d=a[0];e=a[1];return U(e)},function(a){return[d,a[0],a[1]]}):S(c,function(a){d=a[0];e=a[1];return U(e)},function(a){return[d,a[0]]})};Y.prototype.edges_iter=Y.prototype.d;Y.prototype.Y=Y.prototype.d;Y.prototype.out_edges_iter=Y.prototype.Y;Y.prototype.ca=X.prototype.q;Y.prototype.out_edges=Y.prototype.ca;
Y.prototype.C=function(a,b){w(a)&&(b=a,a=m);var c,d;c=a!=m?P(this.b(a),function(a){return[a,this.pred[a]]},this):Eb(this.pred);return b?S(c,function(a){d=a[0];return U(a[1])},function(a){return[a[0],d,a[1]]}):S(c,function(a){d=a[0];return U(a[1])},function(a){return[a[0],d]})};Y.prototype.in_edges_iter=Y.prototype.C;Y.prototype.N=function(a,b){return Q(this.C(a,b))};Y.prototype.in_edges=Y.prototype.N;
Y.prototype.n=function(a,b){var c;c=a!=m?yb(P(this.b(a),function(a){return[a,this.succ[a]]},this),P(this.b(a),function(a){return[a,this.pred[a]]},this)):yb(U(this.succ),U(this.pred));return b?P(c,function(a){var c=a[0][1],f=a[1][1],g=0,j;for(j in c)g+=+J(c[j],b,1);for(j in f)g+=+J(f[j],b,1);return[a[0][0],g]}):P(c,function(a){return[a[0][0],wb(a[0][1])+wb(a[1][1])]})};Y.prototype.degree_iter=Y.prototype.n;
Y.prototype.M=function(a,b){var c;c=a!=m?P(this.b(a),function(a){return[a,this.pred[a]]},this):U(this.pred);return b?P(c,function(a){var c=0,f=a[1],g;for(g in f)c+=+J(f[g],b,1);return[a[0],c]}):P(c,function(a){return[a[0],G(a[1])]})};Y.prototype.in_degree_iter=Y.prototype.M;Y.prototype.S=function(a,b){var c;c=a!=m?P(this.b(a),function(a){return[a,this.succ[a]]},this):U(this.succ);return b?P(c,function(a){var c=0,f=a[1],g;for(g in f)c+=+J(f[g],b,1);return[a[0],c]}):P(c,function(a){return[a[0],G(a[1])]})};
Y.prototype.out_degree_iter=Y.prototype.S;Y.prototype.ha=function(a,b){return this.k(a)?this.M(a,b).next()[1]:tb(this.M(a,b))};Y.prototype.in_degree=Y.prototype.ha;Y.prototype.ja=function(a,b){return this.k(a)?this.S(a,b).next()[1]:tb(this.S(a,b))};Y.prototype.out_degree=Y.prototype.ja;Y.prototype.clear=function(){Va(this.succ);Va(this.pred);Va(this.node);Va(this.graph)};Y.prototype.clear=Y.prototype.clear;Y.prototype.i=ba(n);Y.prototype.is_multigraph=Y.prototype.i;Y.prototype.c=ba(k);
Y.prototype.is_directed=Y.prototype.c;Y.prototype.F=function(){return Fb(this)};Y.prototype.to_directed=Y.prototype.F;Y.prototype.V=function(a){var b=new X;b.name(this.name());b.h(this);var c=this.pred,d;a?b.a(S(this.p(),function(a){d=a[0];return U(a[1])},function(a){if(a[0]in c[d])return[d,a[0],T(a[1])]})):b.a(S(this.p(),function(a){d=a[0];return U(a[1])},function(a){return[d,a[0],T(a[1])]}));b.graph=T(this.graph);b.node=T(this.node);return b};Y.prototype.to_undirected=Y.prototype.V;
Y.prototype.reverse=function(a){(a=!s(a)||a)?(a=new this.constructor(m,{name:"Reverse of ("+this.name()+")"}),a.h(this),a.a(P(this.d(k),function(a){return[a[1],a[0],T(a[2])]})),a.graph=T(this.graph),a.node=T(this.node)):(a=this.succ,this.succ=this.pred,this.pred=a,this.adj=this.succ,a=this);return a};Y.prototype.reverse=Y.prototype.reverse;
Y.prototype.t=function(a){a=this.b(a);var b=new this.constructor,c=b.succ,d=b.pred,e=this.succ;O(a,function(a){c[a]={};d[a]={}});O(c,function(a){var b=c[a];F(e[a],function(e,l){l in c&&(b[l]=e,d[l][a]=e)})});O(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};Y.prototype.subgraph=Y.prototype.t;function Z(a,b){if(!(this instanceof Z))return new Z(a,b);X.call(this,a,b)}oa(Z,X);x("jsnx.classes.MultiGraph",Z);x("jsnx.MultiGraph",Z);Z.__name__="MultiGraph";
Z.prototype.g=function(a,b,c,d){var e,f;c!=m&&(!v(c)&&!ha(c))&&(d=c,c=m);d=d||{};"object"!==r(d)&&h(new M("The attr_dict argument must be an object."));a in this.adj||(this.adj[a]={},this.node[a]={});b in this.adj||(this.adj[b]={},this.node[b]={});if(b in this.adj[a]){f=this.adj[a][b];if(c==m)for(c=G(f);c in f;)c+=1;e=J(f,c,{});K(e,d);f[c]=e}else c!=m||(c=0),e={},K(e,d),f=Ya(c,e),this.adj[a][b]=f,this.adj[b][a]=f};Z.prototype.add_edge=Z.prototype.g;
Z.prototype.a=function(a,b){b=b||{};"object"!==r(b)&&h(new M("The attr_dict argument must be an object."));O(a,function(a){var d=wb(a),e,f,g=m,j={};4===d?(e=a[0],f=a[1],g=a[2],j=a[3]):3===d?(e=a[0],f=a[1],j=a[2]):2===d?(e=a[0],f=a[1]):h(new M("Edge tuple "+Gb(a)+" must be a 2-tuple, 3-tuple or 4-tuple."));a=e in this.adj?J(this.adj[e],f,{}):{};if(g==m)for(g=G(a);g in a;)g+=1;a=J(a,g,{});K(a,b,j);this.g(e,f,g,a)},this)};Z.prototype.add_edges_from=Z.prototype.a;
Z.prototype.s=function(a,b,c){(!(a in this.adj)||!(b in this.adj[a]))&&h(new M("The edge "+a+"-"+b+" is not in the graph"));var d=this.adj[a][b];c!=m?(c in d||h(new M("The edge "+a+"-"+b+" with key "+c+" is not in the graph")),I(d,c)):I(d,Ta(d));0===G(d)&&(I(this.adj[a],b),a!=b&&I(this.adj[b],a))};Z.prototype.remove_edge=Z.prototype.s;Z.prototype.z=function(a){O(a,function(a){try{this.s(a[0],a[1],a[2])}catch(c){c instanceof M||h(c)}},this)};Z.prototype.remove_edges_from=Z.prototype.z;
Z.prototype.B=function(a,b,c){return c!=m?a in this.adj&&b in this.adj[a]&&c in this.adj[a][b]:a in this.adj&&b in this.adj[a]};Z.prototype.has_edge=Z.prototype.B;Z.prototype.q=function(a,b,c){return Ga(this.d(a,b,c))};Z.prototype.edges=Z.prototype.q;
Z.prototype.d=function(a,b,c){w(a)&&(w(b)&&(c=b),b=a,a=m);var d={},e,f;a=a!=m?P(this.b(a),function(a){return[a,this.adj[a]]},this):U(this.adj);return b?S(a,function(a){e=a[0];var b=new B,c=U(a[1]);b.next=function(){try{return c.next()}catch(a){a===z&&(d[e]=1),h(a)}};return b},function(a){f=a[0];if(!(f in d))return U(a[1])},function(a){return c?[e,f,a[0],a[1]]:[e,f,a[1]]}):S(a,function(a){e=a[0];var b=new B,c=U(a[1]);b.next=function(){try{return c.next()}catch(a){a===z&&(d[e]=1),h(a)}};return b},function(a){f=
a[0];if(!(f in d))return U(a[1])},function(a){return c?[e,f,a[0]]:[e,f]})};Z.prototype.edges_iter=Z.prototype.d;Z.prototype.L=function(a,b,c,d){s(d)||(d=m);return a in this.adj&&b in this.adj[a]?c!=m?J(this.adj[a][b],c,d):this.adj[a][b]:d};Z.prototype.get_edge_data=Z.prototype.L;
Z.prototype.n=function(a,b){var c;c=a!=m?P(this.b(a),function(a){return[a,this.adj[a]]},this):U(this.adj);return b!=m?E(c,function(a){var c=a[0];a=a[1];var f=0;F(a,function(a){F(a,function(a){f+=J(a,b,1)})});c in a&&F(a[c],function(a){f+=J(a,b,1)});return[c,f]}):E(c,function(a){var b=a[0];a=a[1];var c=0;F(a,function(a){c+=G(a)});return[b,c+ +(b in a&&G(a[b]))]})};Z.prototype.degree_iter=Z.prototype.n;Z.prototype.i=ba(k);Z.prototype.is_multigraph=Z.prototype.i;Z.prototype.c=ba(n);
Z.prototype.is_directed=Z.prototype.c;Z.prototype.F=function(){var a=new $;a.h(this);a.a(function(){var a,c;return S(this.p(),function(c){a=c[0];return U(c[1])},function(a){c=a[0];return U(a[1])},function(d){return[a,c,d[0],T(d[1])]})}.call(this));a.graph=T(this.graph);a.node=T(this.node);return a};Z.prototype.to_directed=Z.prototype.F;
Z.prototype.U=function(a,b){var c=[];a?b?F(this.adj,function(a,b){b in a&&F(a[b],function(a,d){c.push([b,b,d,a])})}):F(this.adj,function(a,b){b in a&&F(a[b],function(a){c.push([b,b,a])})}):b?F(this.adj,function(a,b){b in a&&F(a[b],function(a,d){c.push([b,b,d])})}):F(this.adj,function(a,b){b in a&&F(a[b],function(){c.push([b,b])})});return c};Z.prototype.selfloop_edges=Z.prototype.U;Z.prototype.J=function(a,b){return a==m?this.size():a in this.adj&&b in this.adj[a]?G(this.adj[a][b]):0};
Z.prototype.number_of_edges=Z.prototype.J;Z.prototype.t=function(a){a=this.b(a);var b=new this.constructor,c=b.adj,d=this.adj;D(a,function(a){var b={};c[a]=b;F(d[a],function(d,j){if(j in c){var l=Wa(d);b[j]=l;c[j][a]=l}})});F(this.node,function(a,c){b.node[c]=a});b.graph=this.graph;return b};Z.prototype.subgraph=Z.prototype.t;function $(a,b){if(!(this instanceof $))return new $(a,b);Y.call(this,a,b)}oa($,Y);var Mb=$.prototype,Nb=Z.prototype,Ob;for(Ob in Nb)Nb.hasOwnProperty(Ob)&&"constructor"!==Ob&&(Mb[Ob]=Nb[Ob]);x("jsnx.classes.MultiDiGraph",$);x("jsnx.MultiDiGraph",$);$.__name__="MultiDiGraph";
$.prototype.g=function(a,b,c,d){var e,f;c!=m&&(!v(c)&&!ha(c))&&(d=c,c=m);d=d||{};"object"!==r(d)&&h(new M("The attr_dict argument must be an object."));a in this.succ||(this.succ[a]={},this.pred[a]={},this.node[a]={});b in this.succ||(this.succ[b]={},this.pred[b]={},this.node[b]={});if(b in this.succ[a]){f=this.adj[a][b];if(c==m)for(c=G(f);c in f;)c+=1;e=J(f,c,{});K(e,d);f[c]=e}else c!=m||(c=0),e={},K(e,d),f=Ya(c,e),this.succ[a][b]=f,this.pred[b][a]=f};$.prototype.add_edge=$.prototype.g;
$.prototype.s=function(a,b,c){(!(a in this.adj)||!(b in this.adj[a]))&&h(new M("The edge "+a+"-"+b+" is not in the graph"));var d=this.adj[a][b];c!=m?(c in d||h(new M("The edge "+a+"-"+b+" with key "+c+" is not in the graph")),I(d,c)):I(d,Ta(d));0===G(d)&&(I(this.succ[a],b),I(this.pred[b],a))};$.prototype.remove_edge=$.prototype.s;
$.prototype.d=function(a,b,c){w(a)&&(w(b)&&(c=b),b=a,a=m);var d,e;a=a!=m?P(this.b(a),function(a){return[a,this.adj[a]]},this):Eb(this.adj);return b?S(a,function(a){d=a[0];return U(a[1])},function(a){e=a[0];return U(a[1])},function(a){return c?[d,e,a[0],a[1]]:[d,e,a[1]]}):S(a,function(a){d=a[0];return U(a[1])},function(a){e=a[0];return U(a[1])},function(a){return c?[d,e,a[0]]:[d,e]})};$.prototype.edges_iter=$.prototype.d;$.prototype.Y=$.prototype.d;$.prototype.out_edges_iter=$.prototype.Y;
$.prototype.ca=function(a,b,c){return Ga(this.Y(a,b,c))};$.prototype.out_edges=$.prototype.ca;$.prototype.C=function(a,b,c){w(a)&&(b=a,a=m);var d,e;a=ea?P(this.b(a),function(a){return[a,this.pred[a]]},this):Eb(this.pred);return b?S(a,function(a){d=a[0];return U(a[1])},function(a){e=a[0];return U(a[1])},function(a){return c?[e,d,a[0],a[1]]:[e,d,a[1]]}):S(a,function(a){d=a[0];return U(a[1])},function(a){e=a[0];return U(a[1])},function(a){return c?[e,d,a[0]]:[e,d]})};$.prototype.in_edges_iter=$.prototype.C;
$.prototype.N=function(a,b,c){return Ga(this.C(a,b,c))};$.prototype.in_edges=$.prototype.N;
$.prototype.n=function(a,b){var c;c=a!=m?yb(E(this.b(a),function(a){return[a,this.succ[a]]},this),E(this.b(a),function(a){return[a,this.pred[a]]},this)):yb(U(this.succ),U(this.pred));return b!=m?P(c,function(a){var c=a[0][1],f=0;F(a[1][1],function(a){F(a,function(a){f+=+J(a,b,1)})});F(c,function(a){F(a,function(a){f+=+J(a,b,1)})});return[a[0][0],f]}):P(c,function(a){var b=0,c=0;F(a[1][1],function(a){b+=wb(a)});F(a[0][1],function(a){c+=wb(a)});return[a[0][0],b+c]})};$.prototype.degree_iter=$.prototype.n;
$.prototype.M=function(a,b){var c;c=a!=m?P(this.b(a),function(a){return[a,this.pred[a]]},this):U(this.pred);return b!=m?P(c,function(a){var c=0;F(a[1],function(a){F(a,function(a){c+=+J(a,b,1)})});return[a[0][0],c]}):P(c,function(a){var b=0;F(a[1],function(a){b+=G(a)});return[a[0],b]})};$.prototype.in_degree_iter=$.prototype.M;
$.prototype.S=function(a,b){var c;c=a!=m?P(this.b(a),function(a){return[a,this.succ[a]]},this):U(this.succ);return b!=m?P(c,function(a){var c=0;F(a[1],function(a){F(a,function(a){c+=+J(a,b,1)})});return[a[0][0],c]}):P(c,function(a){var b=0;F(a[1],function(a){b+=G(a)});return[a[0],b]})};$.prototype.out_degree_iter=$.prototype.S;$.prototype.i=ba(k);$.prototype.is_multigraph=$.prototype.i;$.prototype.c=ba(k);$.prototype.is_directed=$.prototype.c;$.prototype.F=function(){return Fb(this)};
$.prototype.to_directed=$.prototype.F;$.prototype.V=function(a){var b=new Z;b.name(this.name());b.h(this);var c=this,d,e;a?b.a(S(this.p(),function(a){d=a[0];return U(a[1])},function(a){e=a[0];return U(a[1])},function(a){if(c.B(e,d,a[0]))return[d,e,a[0],T(a[1])]})):b.a(S(this.p(),function(a){d=a[0];return U(a[1])},function(a){e=a[0];return U(a[1])},function(a){return[d,e,a[0],T(a[1])]}));b.graph=T(this.graph);b.node=T(this.node);return b};$.prototype.to_undirected=$.prototype.V;
$.prototype.t=function(a){a=this.b(a);var b=new this.constructor,c=b.succ,d=b.pred,e=this.succ;D(a,function(a){c[a]={};d[a]={}});O(c,function(a){var b=c[a];F(e[a],function(e,l){if(l in c){var A=Wa(e);b[l]=A;d[l][a]=A}})});O(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};$.prototype.subgraph=$.prototype.t;
$.prototype.reverse=function(a){(a=!s(a)||a)?(a=new this.constructor(m,{name:"Reverse of ("+this.name()+")"}),a.h(this),a.a(E(this.d(k,k),function(a){return[a[1],a[0],a[2],T(a[3])]})),a.graph=T(this.graph),a.node=T(this.node)):(a=this.succ,this.succ=this.pred,this.pred=a,this.adj=this.succ,a=this);return a};$.prototype.reverse=$.prototype.reverse;x("jsnx.nodes",function(a){return a.nodes()});x("jsnx.nodes_iter",function(a){return a.D()});x("jsnx.edges",function(a,b){return a.q(b)});x("jsnx.edges_iter",function(a,b){return a.d(b)});x("jsnx.degree",function(a,b,c){return a.m(b,c)});x("jsnx.neighbors",function(a,b){return a.I(b)});x("jsnx.number_of_nodes",function(a){return a.R()});x("jsnx.number_of_edges",function(a){return a.J()});x("jsnx.density",function(a){var b=a.R(),c=a.J();return 0===c?0:a.c()?c/(b*(b-1)):2*c/(b*(b-1))});
x("jsnx.degree_histogram",function(a){a=Ua(a.m());for(var b=Math.max.apply(Math,a)+1,c=[],d=0;d<b;d++)c[d]=0;ra(a,function(a){c[a]+=1});return c});x("jsnx.is_directed",function(a){return a.c()});x("jsnx.freeze",function(a){function b(){h(new M("Frozen graph can't be modified"))}a.H=b;a.h=b;a.K=b;a.T=b;a.g=b;a.a=b;a.s=b;a.z=b;a.clear=b;a.ua=k;return a});x("jsnx.is_frozen",function(a){return!!a.ua});x("jsnx.subgraph",function(a,b){return a.t(b)});
x("jsnx.create_empty_copy",function(a,b){s(b)||(b=k);var c=new a.constructor;b&&c.h(a);return c});
x("jsnx.info",function(a,b){var c="";if(b!=m)a.k(b)||h(new M("node "+b+" not in graph")),c=c+("Node "+b+" has the following properties:\n")+("Degree: "+a.m(b)+"\n"),c+="Neighbors: "+a.I(b).join(" ");else{var c=c+("Name: "+a.name()+"\n"),c=c+("Type: "+a.constructor.__name__+"\n"),c=c+("Number of nodes: "+a.R()+"\n"),c=c+("Number of edges: "+a.J()+"\n"),d=a.R();if(0<d)if(a.c())c+="Average in degree: "+(V.o.apply(m,Ua(a.ha()))/d).toFixed(4)+"\n",c+="Average out degree: "+(V.o.apply(m,Ua(a.ja()))/d).toFixed(4);
else var e=V.o.apply(m,Ua(a.m())),c=c+("Average degree: "+(e/d).toFixed(4))}return c});x("jsnx.set_node_attributes",function(a,b,c){F(c,function(c,e){a.ba[e][b]=c})});function Pb(a,b){var c={};F(a.ba,function(a,e){b in a&&(c[e]=a[b])});return c}x("jsnx.get_node_attributes",Pb);x("jsnx.set_edge_attributes",function(a,b,c){F(c,function(b,c){c=c.split(",");a.l(c[0])[c[1]]=b})});Pb=function(a,b){var c={};F(a.q(k),function(a){b in a[2]&&(c[[a[0],a[1]]]=a[2][b])});return c};
x("jsnx.get_edge_attributes",{}.Na);var Qb={};function Rb(a,b){a.c()&&h(new M("triangles() is not defined for directed graphs."));if(a.k(b))return Math.floor(Sb(a,b).next()[2]/2);var c={};D(Sb(a,b),function(a){c[a[0]]=Math.floor(a[2]/2)});return c}x("jsnx.triangles",Rb);
function Sb(a,b){a.i()&&h(new M("Not defined for multigraphs."));var c;c=b!=m?S(a.b(b),function(b){return[b,a.l(b)]}):U(a.adj);return E(c,function(b){var c=new L(H(b[1])),f=0;c.remove(b[0]);D(c,function(b){var d=new L(H(a.l(b)));d.remove(b);f+=cb(c,d).e()});return[b[0],c.e(),f]})}
x("jsnx.average_clustering",function(a,b,c,d){2===arguments.length?v(b)?(c=b,b=m):w(b)&&(d=b,b=m):3===arguments.length&&w(c)&&(d=c,c=m);c!=m||(c=m);d!=m||(d=k);var e=Ua(Tb(a,b,c));d||(e=sa(e,function(a){return 0<a}));return V.o.apply(V,e)/e.length});
function Tb(a,b,c){a.c()&&h(new M("Clustering algorithms are not defined for directed graphs."));if(c!=m){var d=c;a.i()&&h(new M("Not defined for multigraphs."));s(d)||(d="weight");var e;if(0===a.q().length)c=1;else{c=a.q(k);var f=function(a){return J(a[2],d,1)};c=ja(f)?P(c,function(){return f.apply(m,arguments)}):Q(c);c=Math.max.apply(m,c)}e=c;c=b!=m?S(a.b(b),function(b){return[b,a.l(b)]}):U(a.adj);c=E(c,function(b){var c=b[0],f=new L(H(b[1]));f.remove(c);var g=0,t=new L;D(f,function(b){var j=J(a.l(c)[b],
d,1)/e;t.add(b);var W=db(new L(H(a.l(b))),t);D(cb(f,W),function(f){var A=J(a.l(b)[f],d,1)/e;f=J(a.l(c)[f],d,1)/e;g+=Math.pow(j*A*f,1/3)})});return[c,f.e(),2*g]})}else c=Sb(a,b);var g={};D(c,function(a){g[a[0]]=0===a[2]?0:a[2]/(a[1]*(a[1]-1))});return a.k(b)?Ua(g)[0]:g}x("jsnx.clustering",Tb);x("jsnx.transitivity",function(a){var b=0,c=0;D(Sb(a),function(a){c+=a[1]*(a[1]-1);b+=a[2]});return 0===b?0:b/c});
x("jsnx.square_clustering",function(a,b){var c=b==m?a:a.b(b),d={};D(c,function(b){var c=d[b]=0;D(Ab(H(a.l(b))),function(g){var j=g[0];g=g[1];var l=cb(new L(H(a.l(j))),H(a.l(g)));l.remove(b);l=l.e();d[b]+=l;var A=l+1,q=a.l(j);g in q&&(A+=1);c+=(G(a.l(j))-A)*(G(a.l(g))-A)+l});0<c&&(d[b]/=c)});return a.k(b)?Ua(d)[0]:d});function Ub(a){var b=-1,c={},d=new L;D(a.p(),function(a){var e=new L(H(a[1]));e.remove(a[0]);var f=e.e();f>b?(c[a[0]]=d=e,b=f):c[a[0]]=e});var e=new L(H(c)),f=db(e,d),g=new L,j=[],l=[];a=new B;a.next=function(){0===f.e()&&0===j.length&&h(z);var a,q;if(0<f.e())a=La(f),f.remove(a);else{var t=j.pop();e=t[0];g=t[1];f=t[2];l.pop();return this.next()}l.push(a);e.remove(a);g.add(a);var C=c[a],t=cb(e,C),C=cb(g,C);if(0===t.e()&&(0===C.e()&&(q=wa(l)),l.pop(),q))return q;if(0===C.e()&&1===t.e())return q=va(l,
t.A()),l.pop(),q;var ia=t.e(),W=-1,Ha,la;for(q=Da(C);(a=La(q,m))!==m&&!(a=cb(t,c[a]),la=a.e(),la>W&&(Ha=a,W=la,W===ia)););if(W===ia)return l.pop(),this.next();b=-1;for(q=Da(t);(a=La(q,m))!==m&&!(a=cb(t,c[a]),la=a.e(),la>b&&(d=a,b=la,b===ia-1)););W>b&&(d=Ha);j.push([e,g,f]);e=t;g=C;f=db(e,d);return this.next()};return a}x("jsnx.find_cliques",Ub);
x("jsnx.find_cliques_recursive",function(a){var b={};D(a.p(),function(a){var c=new L(H(a[1]));c.remove(a[0]);b[a[0]]=c});a:{for(var c in b){a=n;break a}a=k}if(a)return[];a=new L(H(b));c=new L;var d=[];Vb(b,a,c,[],d);return d});
function Vb(a,b,c,d,e){var f=-1,g=b.e(),j,l,A,q;for(l=Da(c);(A=La(l,m))!==m;)if(A=cb(b,a[A]),q=A.e(),q>f&&(j=A,f=q,q===g))return;D(b,function(c){c=cb(b,a[c]);var d=c.e();d>f&&(j=c,f=d)});g=db(b,j);D(g,function(f){b.remove(f);d.push(f);var g=a[f];f=cb(b,g);g=cb(c,g);f.O()&&g.O()?e.push(wa(d)):g.O()&&1===f.e()?e.push(va(d,f.A())):Vb(a,f,g,d,e);c.add(d.pop())})}x("jsnx.graph_clique_number",function(a,b){b!=m||(b=Ub(a));var c=0;O(b,function(a){c=a.length>c?a.length:c});return c});
x("jsnx.graph_number_of_cliques",function(a,b){b!=m||(b=Ub(a));return Q(b).length});function Wb(a,b,c){c!=m||(c=Ga(Ub(a)));b!=m||(b=a.nodes());var d;if(ga(b))d={},ra(b,function(a){d[a]=sa(c,function(b){return 0<=pa(b,a)||0<=pa(b,a+"")}).length});else{var e=b;d=sa(c,function(a){return 0<=pa(a,e)||0<=pa(a,e+"")}).length}return d}x("jsnx.number_of_cliques",Wb);function Xb(a,b){if(a.w()!=b.w())return n;var c=a.m(),d=Rb(a),e=Wb(a),f=[],g;for(g in c)f.push([c[g],d[g],e[g]]);f.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]!==b[1]?a[1]-b[1]:a[2]-b[2]});var c=b.m(),d=Rb(b),e=Wb(b),j=[];for(g in c)j.push([c[g],d[g],e[g]]);j.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]!==b[1]?a[1]-b[1]:a[2]-b[2]});return!za(f,j,function(a,b){return za(a,b)})?n:k}x("jsnx.algorithms.isomorphism.could_be_isomorphic",Xb);x("jsnx.could_be_isomorphic",Xb);
function Yb(a,b){if(a.w()!=b.w())return n;var c=a.m(),d=Rb(a),e=[],f;for(f in c)e.push([c[f],d[f]]);e.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]-b[1]});var c=b.m(),d=Rb(b),g=[];for(f in c)g.push([c[f],d[f]]);g.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]-b[1]});return!za(e,g,function(a,b){return za(a,b)})?n:k}x("jsnx.algorithms.isomorphism.fast_could_be_isomorphic",Yb);x("jsnx.fast_could_be_isomorphic",Yb);
function Zb(a,b){if(a.w()!=b.w())return n;var c=Ua(a.m());c.sort();var d=Ua(b.m());d.sort();return!za(c,d)?n:k}x("jsnx.algorithms.isomorphism.faster_could_be_isomorphic",Zb);x("jsnx.faster_could_be_isomorphic",Zb);function $b(a,b){if("eg"===b)return ac(a);if(b==m||"hh"===b)return bc(a);h(new nb("`opt_method` must be 'eg' or 'hh'"))}x("jsnx.is_valid_degree_sequence",$b);function bc(a){if(0===a.length)return k;if(!Oa(a)||0>Math.min.apply(m,a)||0!==V.o.apply(m,a)%2)return n;for(a=wa(a);0<a.length;){y.sort.call(a,Ba);if(0>a[0])break;var b=a.pop();if(0===b)return k;if(b>a.length)break;for(var c=a.length-1,b=a.length-(b+1);c>b;c--)a[c]-=1}return n}x("jsnx.is_valid_degree_sequence_havel_hakimi",bc);
function ac(a){if(0===a.length)return k;if(!Oa(a)||0>Math.min.apply(m,a)||0!==V.o.apply(m,a)%2)return n;var b=a.length,c=wa(a).sort(function(a,b){return b-a}),d=[],e;e=1;for(a=c.length;e<a;e++)c[e]<c[e-1]&&d.push(e);var f,g;e=0;for(a=d.length;e<a;e++)if(f=V.o.apply(m,c.slice(0,d[e])),g=d[e]*(d[e]-1)+V.o.apply(m,Ga(E(zb(d[e],b),function(a){return Math.min(d[e],c[a])}))),f>g)return n;return k}x("jsnx.is_valid_degree_sequence_erdos_gallai",ac);function cc(a){var b={},c={},d=new L,e=[],f=[],g=0,j=n;D(a.D(),function(l){var A,q,t,C;if(!d.contains(l))for(C=[l];0<C.length;){l=C[C.length-1];l in b||(g+=1,b[l]=g);j=k;A=a.I(l);for(t=0;t<A.length;t++)if(q=A[t],!(q in b)){C.push(q);j=n;break}if(j){c[l]=b[l];for(t=0;t<A.length;t++)q=A[t],d.contains(q)||(c[l]=b[q]>b[l]?Math.min(c[l],c[q]):Math.min(c[l],b[q]));C.pop();if(c[l]===b[l]){d.add(l);for(A=[l];0<e.length&&b[e[e.length-1]]>b[l];)q=e.pop(),d.add(q),A.push(q);f.push(A)}else e.push(l)}}});f.sort(function(a,
b){return b.length-a.length});return f}x("jsnx.strongly_connected_components",cc);x("jsnx.simple_cycles",function(a){function b(a){function g(a){var b;for(e.remove(a);0<d[a].length;)b=d[a].pop(),e.contains(b)&&g(b)}var j=n,l,C,t=c.ea(a);A.push(a);e.add(a);for(l=0;l<t.length;l++)C=t[l],C===f?(j=A.slice(0),j.push(f),q.push(j),j=k):e.contains(C)||b(C)&&(j=k);if(j)g(a);else for(l=0;l<t.length;l++)C=t[l],0<=pa(d[C],a)||d[C].push(a);a!==A.pop()&&console.log("DANGER WILL ROBINSON!");return j}a.c()||h(new M("simple_cycles() is not defined for undirected graphs."));var c,d={},e=new L,f,
g,j,l=a.nodes(),A=[],q=[],t,C,ia,W={};for(j=0;j<l.length;j++)d[l[j]]=[],W[l[j]]=j;for(g=0;g<l.length-1;)if(f=l[g],j=a.t(l.slice(g)),t=cc(j),0===t.length)g=l.length;else{c=ia=C=aa;for(j=0;j<t.length;j++)for(g=0;g<t[j].length;g++)C===aa?(C=t[j][g],c=t[j],ia=W[C]):W[t[j][g]]<ia&&(C=t[j][g],c=t[j],ia=W[C]);c=a.t(c);f=C;g=W[C];t=c.nodes();for(j=0;j<t.length;j++)e.remove(t[j]),d[t[j]]=[];b(f);g++}return q});var dc,ec=m,gc="add_node add_nodes_from add_edge add_edges_from remove_node remove_nodes_from remove_edge remove_edges_from clear".split(" ");
x("jsnx.draw",function(a,b,c){function d(){N.attr("transform",function(a){return["translate(",a.x,",",a.y,")scale(",fa,")"].join("")});Cb()}w(b)&&(c=b,b=m);b=b||ec||{};var e=b.d3||window.d3,f={};Db(f,nc,b);ec=b;e||h(Error("D3 requried for draw()"));f.element==m&&dc==m&&h(Error("Output element required for draw()"));dc=J(f,"element",dc);e.select(dc).select("svg.jsnx").remove();var g=e.select(dc),j=g.append("svg").classed("jsnx",k).attr("pointer-events","all"),l=j.append("g");b=l.append("g").classed("edges",
k).selectAll("g.edge");var A=l.append("g").classed("nodes",k).selectAll("g.node"),q=e.layout.force(),t=f.width||parseInt(g.style("width"),10),C=f.height||parseInt(g.style("height"),10),ia=f.layout_attr,g=f.nodelist||m,W,Ha,la,fc=a.c(),Pa=f.weighted,N=A,R=b;if(f.with_labels){var ya=f.labels;W="object"===r(ya)?function(a){return J(ya,a.node,"")}:ja(ya)?ya:v(ya)?function(a){return a.data[ya]}:function(a){return a.node}}f.labels=W;if(Pa){var Ia=f.weights;la="object"===r(Ia)?function(a){return J(Ia,a.node,
1)}:ja(Ia)?Ia:v(Ia)?function(a){return J(a.data,Ia,1)}:ba(1)}if(f.with_edge_labels){var Ja=f.edge_labels;Ha=Pa&&!s(Ja)?la:"object"===r(Ja)?function(a){return J(ya,a.node,"")}:ja(Ja)?Ja:v(Ja)?function(a){return a.data[Ja]}:function(a){return a.edge};f.edge_labels=Ha}if(Pa&&f.weighted_stroke){var Pa=Ea(a.d(k),function(a,b){b=la({data:b[2]});return a>b?a:b},0),Dc=e.scale.linear().range([1,f.edge_style["stroke-width"]]).domain([0,Pa]);f.edge_style["stroke-width"]=function(a){return Dc(la.call(this,a))}}j.select("svg.jsnx").remove();
j.attr("width",t+"px").attr("height",C+"px").style("opacity",1E-6).transition().duration(1E3).style("opacity",1);var Ec={size:k,nodes:k,links:k,start:k};O(ia,function(a){if(!(a in Ec))q[a](ia[a])});q.nodes([]).links([]).size([t,C]);var Ra=1,fa=1;if(f.pan_zoom.enabled){var hc=f.pan_zoom.scale,Ka=f.edge_style["stroke-width"];ja(Ka)?f.edge_style["stroke-width"]=function(){var a=Ka.apply(this,arguments);return fa*(+a||parseInt(a,10))}:(Ka=+Ka||parseInt(Ka,10),f.edge_style["stroke-width"]=function(){return fa*
Ka});var gb=n,ic=1,jc=Ra;j.call(e.behavior.zoom().on("zoom",function(){var a=e.event.sourceEvent.shiftKey;(a=hc&&a||!(hc||a))&&!gb?(ic=e.event.scale,jc=Ra,gb=k):!a&&gb&&(gb=n);Ra=a?jc*(e.event.scale/ic):Ra;fa=!a?Ra/e.event.scale:fa;a=e.event.translate;l.attr("transform","translate("+a[0]+","+a[1]+")scale("+e.event.scale+")");l.selectAll("g.edge > .line").style("stroke-width",f.edge_style["stroke-width"]);d()}))}var Cb=da;if(fc){j.append("defs").append("marker").attr("id","Triangle").attr("markerUnits",
"strokeWidth").attr("refX","7").attr("refY","5").attr("viewBox","0 0 10 10").attr("orient","auto").append("path").attr("d","M 0 0 L 10 5 L 0 10 z");f.edge_attr["marker-end"]="url(#Triangle)";f.edge_style.fill="none";var hb=f.layout_attr.linkDistance,Sa=f.edge_offset;ja(hb)||(hb=function(){return f.layout_attr.linkDistance});ga(Sa)&&(Sa=function(){return f.edge_offset});ha(Sa)&&(Sa=function(){return[f.edge_offset,f.edge_offset]});Cb=function(){R.each(function(a){if(a.source!==a.target){var b=e.select(this),
c=a.source.x,d=a.source.y,f=a.target.x,g=a.target.y,j=V.fa(c,d,f,g),f=Math.sqrt(Math.pow(f-c,2)+Math.pow(g-d,2)),g=Sa(a),g=[g[0]*fa,g[1]*fa];b.attr("transform",["translate(",c,",",d,")rotate(",j,")"].join(""));if(c=a.G.B(a.target.node,a.source.node)){var d=hb(a)/3,j=-d/(f/2),l=j*f;b.select(".line").attr("d",["M",g[0],j*g[0],"Q",f/2,-d,f-g[1],-j*(f-g[1])+l].join(" "))}else b.select(".line").attr("d",["M",g[0],"0 L",f-g[1],0].join(" "));g=1/fa;b.select("text").attr("x",f*g/2).attr("y",c?g*(-hb(a)/4):
0).attr("transform","scale("+fa+")")}})}}else Cb=function(){R.each(function(a){if(a.source!==a.target){var b=e.select(this),c=a.source.x,d=a.source.y,g=a.target.x,j=a.target.y;a=V.fa(c,d,g,j);g=Math.sqrt(Math.pow(g-c,2)+Math.pow(j-d,2));j=g/2;b.attr("transform",["translate(",c,",",d,")rotate(",a,")"].join(""));b.select(".line").attr("d",["M 0 0 L",g,"0"].join(" "));f.with_edge_labels&&b.select("text").attr("x",j*(1/fa)).attr("y",0).attr("transform","scale("+fa+")"+(90<a&&279>a?"rotate(180,"+j*(1/
fa)+",0)":""))}})};q.on("tick",d);j=a.D();t=a.d();g&&(c=n,j=a.b(g),t=a.d(g));N=oc(a,j,q,A,f.node_shape,W);R=pc(a,t,q,b,Ha);qc(N,{attr:f.node_attr,style:f.node_style,Q:f.label_style,P:f.label_attr},f.with_labels);rc(R,{attr:f.edge_attr,style:f.edge_style,Q:f.edge_label_style,P:f.edge_label_attr},f.with_edge_labels,m,fc);if(c){sc(a,n);var qa=a.constructor.prototype,ib=f.node_shape,jb={attr:f.node_attr,style:f.node_style,P:f.label_attr,Q:f.label_style},kc={attr:f.edge_attr,style:f.edge_style,P:f.edge_label_attr,
Q:f.edge_label_style},kb=f.labels,lc=f.edge_labels,lb=f.with_labels,mc=f.with_edge_labels,Fc=a.c();a.add_node=a.H=function(a){var b=!this.k(a);qa.add_node.apply(this,arguments);b&&(N=oc(this,[a],q,N,ib,kb));qc(N,jb,lb,[a]);q.start()};a.add_nodes_from=a.h=function(a){var b=sa(Q(a),function(a){return!this.k(u(a)?a[0]:a)},this);qa.add_nodes_from.apply(this,arguments);0<b.length&&(N=oc(this,b,q,N,ib,kb));qc(N,jb,lb,a);q.start()};a.add_edge=a.g=function(b,c){var d=!this.B(b,c),e=[];d&&(e=sa(b==c?[b]:[b,
c],function(a){return!this.k(a)},this));qa.add_edge.apply(a,arguments);0<e.length&&(N=oc(this,e,q,N,ib,kb),qc(N,jb,lb,e));d&&(R=pc(this,[[b,c]],q,R,lc));rc(R,kc,mc,[[b,c]],Fc);q.start()};a.add_edges_from=a.a=function(b){var c=[],d=[],e={},f={},g=this.c();O(b,function(a){var b=a[0];a=a[1];if(!this.B(b,a)&&!([b,a]in e)&&(g||!([a,b]in e)))c.push([b,a]),e[[b,a]]=k,!this.k(b)&&!(b in f)&&(d.push(b),f[b]=k),!this.k(a)&&!(a in f)&&(d.push(a),f[a]=k)},this);qa.add_edges_from.apply(a,arguments);0<d.length&&
(N=oc(this,d,q,N,ib,kb),qc(N,jb,lb,d));0<c.length&&(R=pc(this,c,q,R,lc));rc(R,kc,mc,c,g);q.start()};a.remove_node=a.K=function(b){try{if(this.k(b)){N=tc(this,[b],q,N);var c=this.d([b]);this.c()&&(c=Fa(c,this.C([b])));R=uc(this,c,q,R);q.resume()}}catch(d){}qa.remove_node.apply(a,arguments)};a.remove_nodes_from=a.T=function(b){try{N=tc(this,b,q,N);var c=this.d(b);this.c()&&(c=Fa(c,this.C(b)));R=uc(this,c,q,R);q.resume()}catch(d){}qa.remove_nodes_from.apply(a,arguments)};a.remove_edge=a.s=function(b,
c){try{R=uc(this,[[b,c]],q,R),q.resume()}catch(d){}qa.remove_edge.apply(a,arguments)};a.remove_edges_from=a.z=function(b){try{R=uc(this,b,q,R),q.resume()}catch(c){}qa.remove_edges_from.apply(a,arguments)};a.clear=a.clear=function(){N=N.data([],vc);N.exit().remove();R=R.data([],wc);R.exit().remove();q.nodes([]).links([]).resume();qa.clear.apply(a,arguments)};a.bound=k}else a.bound?sc(a):xc(a);q.start();return q});
function oc(a,b,c,d,e,f){var g=c.nodes();O(b,function(b){var c=a.node[b];b={node:b,data:c,G:a};g.push(b);c.__d3datum__=b});d=d.data(g,vc);b=d.enter().append("g").classed("node",k).call(c.drag);b.append(e).classed("node-shape",k);f&&b.append("text").text(f);return d}
function pc(a,b,c,d,e){var f=c.links();O(b,function(b){var c=b[0],d=b[1];b=b[2]||a.L(c,d);c={edge:[c,d],redge:[d,c],source:a.node[c].__d3datum__,target:a.node[d].__d3datum__,data:b,G:a};f.push(c);b.__d3datum__=c});d=d.data(f,wc);b=d.enter().append("g").classed("edge",k);b.append("path").classed("line",k);e&&b.append("text").text(e);return d}
function qc(a,b,c,d){if(d!=m){var e={};O(d,function(a){e[u(a)?a[0]:a]=k});a=a.filter(function(a){return a.node in e})}var f=a.selectAll(".node-shape");F(b.attr,function(a,b){f.attr(b,a)});F(b.style,function(a,b){f.style(b,a)});if(c){var g=a.selectAll("text");F(b.P,function(a,b){g.attr(b,a)});F(b.Q,function(a,b){g.style(b,a)})}}
function rc(a,b,c,d,e){if(d!=m){var f={};O(d,function(a){f[[a[0],a[1]]]=k});a=a.filter(function(a){return a.edge in f||e||a.redge in f})}var g=a.selectAll(".line");F(b.attr,function(a,b){g.attr(b,a)});F(b.style,function(a,b){g.style(b,a)});if(c){var j=a.selectAll("text");F(b.P,function(a,b){j.attr(b,a)});F(b.Q,function(a,b){j.style(b,a)})}}function vc(a){return a.node}function wc(a){return a.edge}
function tc(a,b,c,d){var e=c.nodes();O(a.b(b),function(b){ua(e,a.node[b].__d3datum__)});d=d.data(e,vc);d.exit().remove();return d}function uc(a,b,c,d){var e=c.links();O(b,function(b){ua(e,J(a.L(b[0],b[1],{}),"__d3datum__",m))});d=d.data(e,wc);d.exit().remove();return d}x("jsnx.is_bound",function(a){return a.bound});function sc(a,b){if(a.bound){var c=a.constructor.prototype;ra(gc,function(b){a[b]=c[b]});delete a.bound;(!s(b)||b)&&xc(a)}}x("jsnx.unbind",sc);
function xc(a){O(a.D(k),function(a){I(a[1],"__d3datum__")});O(a.d(k),function(a){I(a[2],"__d3datum__")})}
var nc={layout_attr:{charge:-120,linkDistance:40},node_shape:"circle",node_attr:{r:10},node_style:{stroke:"#333",fill:"#999",cursor:"pointer"},edge_attr:{},edge_style:{stroke:"#000","stroke-width":2},label_attr:{},label_style:{"text-anchor":"middle","dominant-baseline":"central",cursor:"pointer","-webkit-user-select":"none",fill:"#000"},edge_label_attr:{},edge_label_style:{"font-size":"0.8em","dominant-baseline":"central","text-anchor":"middle","-webkit-user-select":"none"},with_labels:n,with_edge_labels:n,
edge_offset:10,weighted:n,weights:"weight",weighted_stroke:k,pan_zoom:{enabled:k,scale:k}};function yc(a,b){var c=zc(a,b);c.name("complete_graph("+a+")");1<a&&c.a(c.c()?Bb(zb(a)):Ab(zb(a)));return c}x("jsnx.complete_graph",yc);x("jsnx.cycle_graph",function(a,b){var c=Ac(a,b);c.name("cycle_graph("+a+")");1<a&&c.g(a-1,0);return c});function zc(a,b){a instanceof X&&(b=a,a=m);a!=m||(a=0);var c;b!=m?(c=b,c.clear()):c=new X;c.h(zb(a));c.name("empty_graph("+a+")");return c}x("jsnx.empty_graph",zc);x("jsnx.null_graph",function(a){a=zc(0,a);a.name("null_graph()");return a});
function Ac(a,b){var c=zc(a,b);c.name("path_graph("+a+")");c.a(E(zb(a-1),function(a){return[a,a+1]}));return c}x("jsnx.path_graph",Ac);x("jsnx.trivial_graph",function(a){a=zc(1,a);a.name("null_graph()");return a});x("jsnx.fast_gnp_random_graph",function(a,b,c){c!=m||(c=n);var d=zc(a);d.name("fast_gnp_random_graph("+a+","+b+")");if(0>=b||1<=b)return Bc(a,b,c);var e=1,f=-1;b=Math.log(1-b);if(c)for(d=Y(d);e<a;){c=Math.log(1-Math.random());f=f+1+Math.floor(c/b);for(e===f&&(f+=1);f>=a&&e<a;)f-=a,e+=1,e==f&&(f+=1);e<a&&d.g(e,f)}else for(;e<a;){c=Math.log(1-Math.random());for(f=f+1+Math.floor(c/b);f>=e&&e<a;)f-=e,e+=1;e<a&&d.g(e,f)}return d});
function Bc(a,b,c){var d;d=c?Y():X();d.h(zb(a));d.name("gnp_random_graph("+a+","+b+")");if(0>=b)return d;if(1<=b)return yc(a,d);a=d.c()?Bb(zb(a)):Ab(zb(a));D(a,function(a){Math.random()<b&&d.g(a[0],a[1])});return d}x("jsnx.gnp_random_graph",Bc);x("jsnx.binomial_graph",Bc);x("jsnx.erdos_renyi_graph",Bc);x("jsnx.havel_hakimi_graph",function(a,b){$b(a)||h(new M("Invalid degree sequence"));b!=m&&(b.c()&&h(new M("Directed Graph not supported")),b.i()&&h(new M("Havel-Hakimi requires simple graph")));var c=a.length,d=zc(c,b);if(0===c||0===Math.max.apply(m,a))return d;for(c=Ga(E(d,function(b){return[a[b],b]}));0<c.length;){c.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:+a[1]-+b[1]});if(0>c[0][0])return n;var e=c.pop();if(0===e[0])break;if(e[0]>c.length)return n;for(var f=c.length,g=f-e[0];g<f;g++)d.g(e[1],
c[g][1]),c[g][0]-=1}d.name("havel_hakimi_graph "+d.w()+" nodes "+d.size()+" edges");return d});function Cc(a,b,c){var d=b;ja(b)&&(d={},D(a.D(),function(a){d[a]=b(a)}));var e;if(!s(c)||c){var f=d,g=new a.constructor;g.name("("+a.name()+")");a.i()?g.a(E(a.d(k,k),function(a){return[J(f,a[0],a[0]),J(f,a[1],a[1]),a[2],Wa(a[3])]})):g.a(E(a.d(k),function(a){return[J(f,a[0],a[0]),J(f,a[1],a[1]),Wa(a[2])]}));g.h(E(a,function(a){return J(f,a,a)}));c={};for(e in a.node)c[J(f,e,e)]=Wa(a.node[e]);K(g.node,c);K(g.graph,Wa(a.graph));e=g}else{var j=d;e=new L(H(j));if(0<cb(e,j).e()){e=Y(Eb(j));e.z(e.U());try{g=
Qb.Ma.$a(e)}catch(l){l instanceof qb&&h(new qb("The node label sets are overlapping and no ordering can resolve the mapping. Use copy=True."))}g.reverse()}else g=e;var A=a.i(),q=a.c(),t;D(g,function(b){var c;b in j&&(c=j[b],a.k(b)||h(new M("Node "+b+" is not in the graph.")),a.H(c,a.node[b]),A?(t=ta(a.q(b,k,k),function(a){return[c,a[1],a[2],a[3]]}),q&&(t=va(t,ta(a.N(b,k,k),function(a){return[a[0],c,a[2],a[3]]})))):(t=ta(a.q(b,k),function(a){return[c,a[1],a[2]]}),q&&(t=va(t,ta(a.N(b,k),function(a){return[a[0],
c,a[2]]})))),a.K(b),a.a(t))});e=a}return e}x("jsnx.relabel_nodes",Cc);
x("jsnx.convert_node_labels_to_integers",function(a,b,c,d){3===arguments.length&&w(c)?(d=c,c=m):2===arguments.length&&(w(b)?(d=b,b=m):v(b)&&(c=b,b=m));b!=m||(b=0);c!=m||(c="default");d!=m||(d=k);var e={},f,g,j,l;if("default"===c){f=a.nodes();g=0;j=b;for(l=f.length;g<l;g++,j++)e[f[g]]=j}else if("sorted"===c){f=a.nodes();f.sort();g=0;j=b;for(l=f.length;g<l;g++,j++)e[f[g]]=j}else if("increasing degree"===c){f=Ga(a.n());f.sort(function(a,b){return a[1]-b[1]});g=0;j=b;for(l=f.length;g<l;g++,j++)e[f[g][0]]=
j}else if("decreasing degree"===c){f=Ga(a.n());f.sort(function(a,b){return b[1]-a[1]});g=0;j=b;for(l=f.length;g<l;g++,j++)e[f[g][0]]=j}else h(new M("Unkown node ordering: "+c));g=Cc(a,e);g.name("("+a.name()+")_with_int_labels");d||(g.node_labels=e);return g});}());
