(function(){function h(a){throw a;}var aa=void 0,k=!0,l=null,n=!1;function ba(a){return function(){return a}}var p,ca=this;
function q(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function r(a){return a!==aa}function da(a){return a!=l}function ea(a){return"array"==q(a)}function s(a){var b=q(a);return"array"==b||"object"==b&&"number"==typeof a.length}function u(a){return"string"==typeof a}function v(a){return"boolean"==typeof a}function fa(a){var b=typeof a;return"object"==b&&a!=l||"function"==b}var ga="closure_uid_"+(1E9*Math.random()>>>0),ha=0;
function w(a,b){var c=a.split("."),d=ca;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&r(b)?d[e]=b:d=d[e]?d[e]:d[e]={}}function ia(a,b){function c(){}c.prototype=b.prototype;a.Va=b.prototype;a.prototype=new c;a.prototype.constructor=a};var z=Array.prototype,ja=z.indexOf?function(a,b,c){return z.indexOf.call(a,b,c)}:function(a,b,c){c=c==l?0:0>c?Math.max(0,a.length+c):c;if(u(a))return!u(b)||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ka=z.forEach?function(a,b,c){z.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=u(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},la=z.filter?function(a,b,c){return z.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,g=u(a)?
a.split(""):a,j=0;j<d;j++)if(j in g){var m=g[j];b.call(c,m,j,a)&&(e[f++]=m)}return e},A=z.map?function(a,b,c){return z.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=u(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};function na(a){return z.concat.apply(z,arguments)}function oa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function pa(a,b,c){return 2>=arguments.length?z.slice.call(a,b):z.slice.call(a,b,c)}
function qa(a,b,c){if(!s(a)||!s(b)||a.length!=b.length)return n;var d=a.length;c=c||ra;for(var e=0;e<d;e++)if(!c(a[e],b[e]))return n;return k}function sa(a,b){return a>b?1:a<b?-1:0}function ra(a,b){return a===b}function ta(a){if(!arguments.length)return[];for(var b=[],c=0;;c++){for(var d=[],e=0;e<arguments.length;e++){var f=arguments[e];if(c>=f.length)return b;d.push(f[c])}b.push(d)}};var B="StopIteration"in ca?ca.StopIteration:Error("StopIteration");function C(){}C.prototype.next=function(){h(B)};C.prototype.t=function(){return this};function ua(a){if(a instanceof C)return a;if("function"==typeof a.t)return a.t(n);if(s(a)){var b=0,c=new C;c.next=function(){for(;;){b>=a.length&&h(B);if(b in a)return a[b++];b++}};return c}h(Error("Not implemented"))}
function E(a,b,c){if(s(a))try{ka(a,b,c)}catch(d){d!==B&&h(d)}else{a=ua(a);try{for(;;)b.call(c,a.next(),aa,a)}catch(e){e!==B&&h(e)}}}function F(a,b,c){var d=ua(a);a=new C;a.next=function(){for(;;){var a=d.next();return b.call(c,a,aa,d)}};return a}function va(a){if(s(a))return oa(a);a=ua(a);var b=[];E(a,function(a){b.push(a)});return b}function wa(a,b){try{return ua(a).next()}catch(c){return c!=B&&h(c),b}};function xa(){}xa.ca=function(){return xa.ea?xa.ea:xa.ea=new xa};xa.prototype.va=0;xa.ca();var ya={};function Aa(a){if(!s(a))return n;for(var b=0,c=a.length;b<c;b++)if(window.isNaN(a[b]))return n;return k}w("jsnx.utils.is_list_of_ints",Aa);w("jsnx.utils.cumulative_sum",function(a){var b=0;return F(a,function(a){return b+=a})});w("jsnx.utils.generate_unique_node",function(){return":"+(xa.ca().va++).toString(36)});function G(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Ba(a,b,c){var d={},e;for(e in a)d[e]=b.call(c,a[e],e,a);return d}function H(a){var b=0,c;for(c in a)b++;return b}function Ca(a){for(var b in a)return b}function I(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function J(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function Da(a){for(var b in a)delete a[b]}function K(a,b){b in a&&delete a[b]}function L(a,b,c){return b in a?a[b]:c}
function Ea(a){var b={},c;for(c in a)b[c]=a[c];return b}var Fa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function M(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Fa.length;f++)c=Fa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}}
function Ga(a){var b=arguments.length;if(1==b&&ea(arguments[0]))return Ga.apply(l,arguments[0]);b%2&&h(Error("Uneven number of arguments"));for(var c={},d=0;d<b;d+=2)c[arguments[d]]=arguments[d+1];return c};function Ha(a){if("function"==typeof a.w)return a.w();if(u(a))return a.split("");if(s(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return I(a)};function Ia(a,b){this.e={};this.g=[];var c=arguments.length;if(1<c){c%2&&h(Error("Uneven number of arguments"));for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.W(a)}p=Ia.prototype;p.u=0;p.Q=0;p.c=function(){return this.u};p.w=function(){Ja(this);for(var a=[],b=0;b<this.g.length;b++)a.push(this.e[this.g[b]]);return a};p.J=function(){return 0==this.u};p.clear=function(){this.e={};this.Q=this.u=this.g.length=0};
p.remove=function(a){return Object.prototype.hasOwnProperty.call(this.e,a)?(delete this.e[a],this.u--,this.Q++,this.g.length>2*this.u&&Ja(this),k):n};function Ja(a){if(a.u!=a.g.length){for(var b=0,c=0;b<a.g.length;){var d=a.g[b];Object.prototype.hasOwnProperty.call(a.e,d)&&(a.g[c++]=d);b++}a.g.length=c}if(a.u!=a.g.length){for(var e={},c=b=0;b<a.g.length;)d=a.g[b],Object.prototype.hasOwnProperty.call(e,d)||(a.g[c++]=d,e[d]=1),b++;a.g.length=c}}
p.set=function(a,b){Object.prototype.hasOwnProperty.call(this.e,a)||(this.u++,this.g.push(a),this.Q++);this.e[a]=b};p.W=function(a){var b;a instanceof Ia?(Ja(a),b=a.g.concat(),a=a.w()):(b=J(a),a=I(a));for(var c=0;c<b.length;c++)this.set(b[c],a[c])};p.R=function(){return new Ia(this)};
p.t=function(a){Ja(this);var b=0,c=this.g,d=this.e,e=this.Q,f=this,g=new C;g.next=function(){for(;;){e!=f.Q&&h(Error("The map has changed since the iterator was created"));b>=c.length&&h(B);var g=c[b++];return a?g:d[g]}};return g};function N(a){this.e=new Ia;a&&this.W(a)}function Ka(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+(a[ga]||(a[ga]=++ha)):b.substr(0,1)+a}p=N.prototype;p.c=function(){return this.e.c()};p.add=function(a){this.e.set(Ka(a),a)};p.W=function(a){a=Ha(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])};p.remove=function(a){return this.e.remove(Ka(a))};p.clear=function(){this.e.clear()};p.J=function(){return this.e.J()};
p.contains=function(a){a=Ka(a);return Object.prototype.hasOwnProperty.call(this.e.e,a)};function La(a,b){for(var c=new N,d=Ha(b),e=0;e<d.length;e++){var f=d[e];a.contains(f)&&c.add(f)}return c}function Ma(a,b){for(var c=a.R(),d=Ha(b),e=d.length,f=0;f<e;f++)c.remove(d[f]);return c}p.w=function(){return this.e.w()};p.R=function(){return new N(this)};p.t=function(){return this.e.t(n)};function Na(a){if(a!=l)try{a.clear()}catch(b){h(Error("Input graph is not a jsnx graph type"))}else a=new ya.Ba;return a}
function Oa(a,b,c){var d;if(a.hasOwnProperty("adj"))try{return d=Pa(a.adj,b,a.f()),"graph"in a&&"object"===q(a.graph)&&(d.graph=Ea(a.graph)),"node"in a&&"object"===q(a.node)&&(d.node=Ba(a.node,function(a){return Ea(a)})),d}catch(e){h(Error("Input is not a correct jsnx graph"))}if("object"===q(a))try{return Pa(a,b,c)}catch(f){try{var g=Na(b);g.i(a);if(g.f()&&!g.d()){var j={};G(a,function(a,b){ka(a,function(a){a in j||g.h(b,a)});j[b]=1})}else{var m=[];G(a,function(a,b){ka(a,function(a){m.push([b,a])})});
g.a(m)}return g}catch(y){h(Error("Input is not known type."))}}if(s(a))try{var x=Na(b);x.a(a);return x}catch(t){h(Error("Input is not valid edge list"))}}w("jsnx.to_networkx_graph",Oa);w("jsnx.convert_to_undirected",ya.Ia);w("jsnx.convert_to_undirected",ya.Ha);w("jsnx.to_dict_of_lists",ya.Wa);
function Pa(a,b,c){var d=Na(b),e,f;d.i(a);c?d.d()?(d.f()?(e=[],G(a,function(a,b){s(a)&&h(Error());G(a,function(a,c){G(a,function(a,d){e.push([b,c,d,a])})})})):(e=[],G(a,function(a,b){s(a)&&h(Error());G(a,function(a,c){G(a,function(a){e.push([b,c,a])})})})),d.a(e)):d.f()?(f=new N,G(a,function(a,b){s(a)&&h(Error());G(a,function(a,c){f.contains([b,c].toString())||(e=[],G(a,function(a,d){e.push([b,c,d,a])}),d.a(e),f.add([c,b].toString()))})})):(f=new N,G(a,function(a,b){s(a)&&h(Error());G(a,function(a,
c){f.contains([b,c].toString())||(e=[],G(a,function(a){e.push([b,c,a])}),d.a(e),f.add([c,b].toString()))})})):d.f()&&!d.d()?(f=new N,G(a,function(a,b){s(a)&&h(Error());G(a,function(a,c){f.contains([b,c].toString())||(d.h(b,c,a),f.add([c,b].toString()))})})):(e=[],G(a,function(a,b){s(a)&&h(Error());G(a,function(a,c){e.push([b,c,a])})}),d.a(e));return d};function Qa(a){this.name="JSNetworkXException";this.message=a}Qa.prototype=Error();Qa.prototype.constructor=Qa;w("jsnx.JSNetworkXException",Qa);function O(a){Qa.call(this,a);this.name="JSNetworkXError"}ia(O,Qa);w("jsnx.JSNetworkXError",O);function Ra(a){Qa.call(this,a);this.name="JSNetworkXPointlessConcept"}ia(Ra,Qa);w("jsnx.JSNetworkXPointlessConcept",Ra);function Sa(a){Qa.call(this,a);this.name="JSNetworkXAlgorithmError"}ia(Sa,Qa);w("jsnx.JSNetworkXAlgorithmError",Sa);
function Ta(a){Sa.call(this,a);this.name="JSNetworkXUnfeasible"}ia(Ta,Sa);w("jsnx.JSNetworkXUnfeasible",Ta);function Ua(a){Ta.call(this,a);this.name="JSNetworkXNoPath"}ia(Ua,Ta);w("jsnx.JSNetworkXNoPath",Ua);function Va(a){Sa.call(this,a);this.name="JSNetworkXUnbounded"}ia(Va,Sa);w("jsnx.JSNetworkXUnbounded",Va);function Wa(a){function b(a,b){a[b[0]]=b[1];return a}a=Xa(a);var c={};E(a,function(a){c=b.call(aa,c,a)});return c}function Ya(a){return a instanceof C||"function"==q(a.t)}function Za(a){if(u(a)||s(a)||"length"in a)return a.length;if($a(a))return H(a);h(new TypeError)}function P(a,b,c,d){v(c)&&(d=c,c=l);if(d){var e=b;b=function(a){e.apply(this,a)}}Ya(a)?E(a,b,c):s(a)||u(a)?ka(a,b,c):fa(a)&&P(J(a),b,c)}w("jsnx.forEach",P);
function Q(a,b,c){if(s(a))return A(a,b,c);if(Ya(a))return F(a,b,c);if(fa(a))return Ba(a,b,c);h(new TypeError)}function ab(){var a=arguments,b=a[0];if(s(b))return ta.apply(l,a);if(Ya(b)){var b=new C,c=a.length;b.next=function(){for(var b=[],e=0;e<c;e++)b.push(a[e].next());return b};return b}if(fa(b))return ta.apply(l,A(a,J));h(new TypeError)}
function bb(a,b,c){if(0===arguments.length)return[];1===arguments.length?(b=a,a=0,c=1):2===arguments.length?c=1:3===arguments.length&&0===arguments[2]&&h("range() step argument must not be zero");var d=new C,e=0>c,f=a,g;d.next=function(){(e&&f<=b||!e&&f>=b)&&h(B);g=f;f+=c;return g};return d}
function cb(a){var b=R(a),c=b.length;if(2>c)return new C;var d=R(bb(2));a=new C;a.next=function(){var a=A(d,function(a){return b[a]});this.next=function(){var a=n,e;for(e=2;e--;)if(d[e]!=e+c-2){a=k;break}a||h(B);d[e]+=1;for(a=e+1;2>a;a++)d[a]=d[a-1]+1;return A(d,function(a){return b[a]})};return a};return a}
function db(a){var b=R(a),c=b.length;if(2>c)return new C;var d=R(bb(c)),e=R(bb(c,c-2,-1));a=new C;var f=new C,g,j=k;a.next=function(){this.next=g.next;return A(d.slice(0,2),function(a){return b[a]})};f.next=function(){return j};g=S(f,function(a){a||h(B);j=n;return bb(1,-1,-1)},function(a){if(!j)if(e[a]-=1,0===e[a])d.splice.apply(d,[a,d.length].concat(d.slice(a+1).concat([d[a]]))),e[a]=c-a;else{var f=e[a],g=d[a];d[a]=d[d.length-f];d[d.length-f]=g;j=k;return Xa([A(d.slice(0,2),function(a){return b[a]})])}},
function(a){return a});return a}function R(a){if(s(a))return oa(a);if(Ya(a))return va(a);if(fa(a))return J(a);h(new TypeError)}w("jsnx.toArray",R);function eb(a){var b=[];G(a,function(a,d){b.push([d,a])});return b}function T(a){var b=new C,c=ua(J(a));b.next=function(){var b=c.next();return[b,a[b]]};return b}function Xa(a){"object"===q(a)&&(!s(a)&&!Ya(a))&&(a=J(a));return ua(a)}
function S(a){var b=new C,c=pa(arguments,1);if(0===c.length)return a;try{a=ua(a)}catch(d){return b.next=function(){"Not implemented"===d.message&&h(new TypeError)},b}var e=l;b.next=function(){var d,g;try{for(;!r(d);)d=e.next()}catch(j){for(;!r(g)||!r(d);)g=a.next(),d=c[0](g);if(Ya(d))return e=S.apply(l,na([d],pa(c,1))),b.next();e=l}return d};return b}w("jsnx.sentinelIterator",function(a,b){var c=new C;c.next=function(){return wa(a,b)};return c});
function $a(a){var b=Object.prototype.hasOwnProperty;if(!a||"object"!==q(a)||a.nodeType||a==a.window)return n;try{if(a.constructor&&!b.call(a,"constructor")&&!b.call(a.constructor.prototype,"isPrototypeOf"))return n}catch(c){return n}for(var d in a);return d===aa||b.call(a,d)}
function U(a,b){b=b||[];var c=q(a);if("object"==c&&$a(a)||"array"==c){var d;d=b;var e;a:{e=function(b){return a===b[0]};for(var f=d.length,g=u(d)?d.split(""):d,j=0;j<f;j++)if(j in g&&e.call(aa,g[j])){e=j;break a}e=-1}d=0>e?l:u(d)?d.charAt(e):d[e];if(d!==l)return d[1];if(a.R)return d=[a,a.R()],b.push(d),d[1];c="array"==c?[]:{};d=[a,c];b.push(d);for(var m in a)c[m]=U(a[m],b);return c}return a}
function fb(a){function b(){}var c={},d;b.prototype=a.constructor.prototype;for(d in a)a.hasOwnProperty(d)&&(c[d]=a[d]);c=U(c);a=new b;for(d in c)a[d]=c[d];return a};function gb(a){var b=[];hb(new ib,a,b);return b.join("")}function ib(){this.V=aa}
function hb(a,b,c){switch(typeof b){case "string":jb(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==l){c.push("null");break}if(ea(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],hb(a,a.V?a.V.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),jb(f,c),c.push(":"),
hb(a,a.V?a.V.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:h(Error("Unknown type: "+typeof b))}}var kb={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},lb=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function jb(a,b){b.push('"',a.replace(lb,function(a){if(a in kb)return kb[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return kb[a]=e+b.toString(16)}),'"')};var V={Qa:function(a){return Math.floor(Math.random()*a)},Ya:function(a,b){return a+Math.random()*(b-a)},Ga:function(a,b,c){return Math.min(Math.max(a,b),c)},ua:function(a,b){var c=a%b;return 0>c*b?c+b:c},Na:function(a,b,c){return a+c*(b-a)},Pa:function(a,b,c){return Math.abs(a-b)<=(c||1E-6)},aa:function(a){return V.ua(a,360)},ha:function(a){return a*Math.PI/180},Aa:function(a){return 180*a/Math.PI},Ea:function(a,b){return b*Math.cos(V.ha(a))},Fa:function(a,b){return b*Math.sin(V.ha(a))},Ca:function(a,
b,c,d){return V.aa(V.Aa(Math.atan2(d-b,c-a)))},Da:function(a,b){var c=V.aa(b)-V.aa(a);180<c?c-=360:-180>=c&&(c=360+c);return c},Ta:function(a){return 0==a?0:0>a?-1:1},Oa:function(a,b,c,d){c=c||function(a,b){return a==b};d=d||function(b){return a[b]};for(var e=a.length,f=b.length,g=[],j=0;j<e+1;j++)g[j]=[],g[j][0]=0;for(var m=0;m<f+1;m++)g[0][m]=0;for(j=1;j<=e;j++)for(m=1;m<=e;m++)g[j][m]=c(a[j-1],b[m-1])?g[j-1][m-1]+1:Math.max(g[j-1][m],g[j][m-1]);for(var y=[],j=e,m=f;0<j&&0<m;)c(a[j-1],b[m-1])?(y.unshift(d(j-
1,m-1)),j--,m--):g[j-1][m]>g[j][m-1]?j--:m--;return y},n:function(a){var b;b=arguments;var c=function(a,b){return a+b};if(b.reduce)b=b.reduce(c,0);else{var d=0;ka(b,function(a){d=c.call(aa,d,a)});b=d}return b},oa:function(a){return V.n.apply(l,arguments)/arguments.length},Ua:function(a){var b=arguments.length;if(2>b)return 0;var c=V.oa.apply(l,arguments),b=V.n.apply(l,A(arguments,function(a){return Math.pow(a-c,2)}))/(b-1);return Math.sqrt(b)},Ma:function(a){return isFinite(a)&&0==a%1},La:function(a){return isFinite(a)&&
!isNaN(a)},Sa:function(a,b){return Math.floor(a+(b||2E-15))},Ra:function(a,b){return Math.ceil(a-(b||2E-15))}};function W(a,b){if(!(this instanceof W))return new W(a,b);this.graph={};this.node={};this.adj={};a!=l&&Oa(a,this);M(this.graph,b||{});this.edge=this.adj}w("jsnx.classes.Graph",W);w("jsnx.Graph",W);W.__name__="Graph";W.prototype.ra=l;W.prototype.graph=W.prototype.ra;W.prototype.Z=l;W.prototype.node=W.prototype.Z;W.prototype.ma=l;W.prototype.adj=W.prototype.ma;W.prototype.pa=l;W.prototype.edge=W.prototype.pa;
W.prototype.name=function(a){if(r(a))this.graph.name=a.toString();else return this.graph.name||""};W.prototype.name=W.prototype.name;W.prototype.toString=function(){return this.name()};W.prototype.toString=W.prototype.toString;W.prototype.t=function(){return Xa(this.adj)};W.prototype.__iterator__=W.prototype.t;W.prototype.k=function(a){a in this.adj||h({name:"KeyError",message:"Graph does not contain node "+a+"."});return this.adj[a]};W.prototype.get_node=W.prototype.k;
W.prototype.F=function(a,b){b!=l||(b={});"object"!==q(b)&&h(new O("The attr_dict argument must be an object."));a in this.adj?M(this.node[a],b||{}):(this.adj[a]={},this.node[a]=b||{})};W.prototype.add_node=W.prototype.F;W.prototype.i=function(a,b){var c,d,e,f,g;b=b||{};P(a,function(a){c=!(a in this.adj);ea(a)?(d=a[0],e=a[1],d in this.adj?(g=this.node[d],M(g,b,e)):(this.adj[d]={},f=Ea(b),M(f,e),this.node[d]=f)):c?(this.adj[a]={},this.node[a]=Ea(b)):M(this.node[a],b)},this)};
W.prototype.add_nodes_from=W.prototype.i;W.prototype.N=function(a){var b=this.adj,c;a in this.node||h(new O("The node "+a+" is not in the graph"));c=J(b[a]);K(this.node,a);ka(c,function(c){K(b[c],a)});K(b,a)};W.prototype.remove_node=W.prototype.N;W.prototype.U=function(a){var b=this.adj;P(a,function(a){try{K(this.node,a),G(b[a],function(d,f){K(b[f],a)}),K(b,a)}catch(d){}},this)};W.prototype.remove_nodes_from=W.prototype.U;W.prototype.K=function(a){return a?T(this.node):Xa(J(this.adj))};
W.prototype.nodes_iter=W.prototype.K;W.prototype.z=function(a){return va(this.K(a))};W.prototype.nodes=W.prototype.z;W.prototype.L=function(){return H(this.adj)};W.prototype.number_of_nodes=W.prototype.L;W.prototype.v=function(){return H(this.adj)};W.prototype.order=W.prototype.v;W.prototype.q=function(a){return!ea(a)&&a in this.adj};W.prototype.has_node=W.prototype.q;
W.prototype.h=function(a,b,c){c=c||{};"object"!==q(c)&&h(new O("The attr_dict argument must be an object."));a in this.adj||(this.adj[a]={},this.node[a]={});b in this.adj||(this.adj[b]={},this.node[b]={});var d=L(this.adj[a],b,{});M(d,c);this.adj[a][b]=d;this.adj[b][a]=d};W.prototype.add_edge=W.prototype.h;
W.prototype.a=function(a,b){b=b||{};"object"!==q(b)&&h(new O("The attr_dict argument must be an object."));P(a,function(a){var d=Za(a),e,f,g;3===d?(e=a[0],f=a[1],g=a[2]):2===d?(e=a[0],f=a[1],g={}):h(new O("Edge tuple "+a.toString()+" must be a 2-tuple or 3-tuple."));e in this.adj||(this.adj[e]={},this.node[e]={});f in this.adj||(this.adj[f]={},this.node[f]={});a=L(this.adj[e],f,{});M(a,b,g);this.adj[e][f]=a;this.adj[f][e]=a},this)};W.prototype.add_edges_from=W.prototype.a;
W.prototype.la=function(a,b,c){c=c||{};u(b)||(c=b,b="weight");this.a(Q(a,function(a){var c={};c[b]=a[2];r(c[b])||h(new TypeError("Values must consist of three elements: "+gb(a)));return[a[0],a[1],c]}),c)};W.prototype.add_weighted_edges_from=W.prototype.la;W.prototype.s=function(a,b){try{K(this.adj[a],b),a!=b&&K(this.adj[b],a)}catch(c){c instanceof TypeError&&h(new O("The edge "+a+"-"+b+" is not in the graph")),h(c)}};W.prototype.remove_edge=W.prototype.s;
W.prototype.A=function(a){P(a,function(a){var c=a[0];a=a[1];c in this.adj&&a in this.adj[c]&&(K(this.adj[c],a),c!=a&&K(this.adj[a],c))},this)};W.prototype.remove_edges_from=W.prototype.A;W.prototype.S=function(a,b){return a in this.adj&&b in this.adj[a]};W.prototype.has_edge=W.prototype.S;W.prototype.C=function(a){a in this.adj||h(new O("The node "+a+" is not in the graph."));return R(this.adj[a])};W.prototype.neighbors=W.prototype.C;
W.prototype.Y=function(a){a in this.adj||h(new O("The node "+a+" is not in the graph."));return Xa(this.adj[a])};W.prototype.neighbors_iter=W.prototype.Y;W.prototype.p=function(a,b){return R(this.j(a,b))};W.prototype.edges=W.prototype.p;
W.prototype.j=function(a,b){v(a)&&(b=a,a=l);var c={},d,e;d=a!=l?Q(this.b(a),function(a){return[a,this.adj[a]]},this):T(this.adj);return b?S(d,function(a){e=a[0];var b=new C,d=T(a[1]);b.next=function(){try{return d.next()}catch(a){a===B&&(c[e]=1),h(a)}};return b},function(a){if(!(a[0]in c))return[e,a[0],a[1]]}):S(d,function(a){e=a[0];var b=new C,d=Xa(a[1]);b.next=function(){try{return d.next()}catch(a){a===B&&(c[e]=1),h(a)}};return b},function(a){if(!(a in c))return[e,a]})};
W.prototype.edges_iter=W.prototype.j;W.prototype.X=function(a,b,c){r(c)||(c=l);return a in this.adj?L(this.adj[a],b,c):c};W.prototype.get_edge_data=W.prototype.X;W.prototype.na=function(){return R(Q(this.o(),function(a){return J(a[1])}))};W.prototype.adjacency_list=W.prototype.na;W.prototype.o=function(){return T(this.adj)};W.prototype.adjacency_iter=W.prototype.o;W.prototype.l=function(a,b){return this.q(a)?this.m(a,b).next()[1]:Wa(va(this.m(a,b)))};W.prototype.degree=W.prototype.l;
W.prototype.m=function(a,b){var c;c=a!=l?Q(this.b(a),function(a){return[a,this.adj[a]]},this):T(this.adj);return b?Q(c,function(a){var c=a[0];a=a[1];var f=0,g;for(g in a)f+=+L(a[g],b,1);f+=+(c in a&&L(a[c],b,1));return[c,f]}):Q(c,function(a){return[a[0],H(a[1])+ +(a[0]in a[1])]})};W.prototype.degree_iter=W.prototype.m;W.prototype.clear=function(){this.name("");Da(this.adj);Da(this.node);Da(this.graph)};W.prototype.clear=W.prototype.clear;W.prototype.copy=function(){return fb(this)};
W.prototype.copy=W.prototype.copy;W.prototype.f=ba(n);W.prototype.is_multigraph=W.prototype.f;W.prototype.d=ba(n);W.prototype.is_directed=W.prototype.d;W.prototype.B=function(){var a=new X;a.name(this.name());a.i(this);a.a(function(){var a;return S(this.o(),function(c){a=c[0];return T(c[1])},function(c){return[a,c[0],U(c[1])]})}.call(this));a.graph=U(this.graph);a.node=U(this.node);return a};W.prototype.to_directed=W.prototype.B;W.prototype.P=function(){return fb(this)};
W.prototype.to_undirected=W.prototype.P;W.prototype.r=function(a){a=this.b(a);var b=new this.constructor,c=b.adj,d=this.adj;P(a,function(a){var b={};c[a]=b;G(d[a],function(d,j){j in c&&(b[j]=d,c[j][a]=d)})});P(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};W.prototype.subgraph=W.prototype.r;W.prototype.wa=function(){return A(la(eb(this.adj),function(a){return a[0]in a[1]}),function(a){return a[0]})};W.prototype.nodes_with_selfloops=W.prototype.wa;
W.prototype.O=function(a){return a?A(la(eb(this.adj),function(a){return a[0]in a[1]}),function(a){var c=a[0];return[c,c,a[1][c]]}):A(la(eb(this.adj),function(a){return a[0]in a[1]}),function(a){return[a[0],a[0]]})};W.prototype.selfloop_edges=W.prototype.O;W.prototype.xa=function(){return this.O().length};W.prototype.number_of_selfloops=W.prototype.xa;W.prototype.size=function(a){var b=V.n.apply(l,I(this.l(l,a)))/2;return a!=l?b:Math.floor(b)};W.prototype.size=W.prototype.size;
W.prototype.D=function(a,b){return a==l?Math.floor(this.size()):b in this.adj[a]?1:0};W.prototype.number_of_edges=W.prototype.D;W.prototype.ka=function(a,b){var c=R(a),d=c[0],c=Q(pa(c,1),function(a){return[d,a]});this.a(c,b)};W.prototype.add_star=W.prototype.ka;W.prototype.ja=function(a,b){var c=R(a),c=ta(pa(c,0,c.length-1),pa(c,1));this.a(c,b)};W.prototype.add_path=W.prototype.ja;W.prototype.ia=function(a,b){var c=R(a),c=ta(c,na(pa(c,1),[c[0]]));this.a(c,b)};W.prototype.add_cycle=W.prototype.ia;
W.prototype.b=function(a){if(a!=l)if(this.q(a))a=Xa([a.toString()]);else{var b=this.adj,c=new C,d=S(a,function(a){if(a in b)return a.toString()});c.next=function(){try{return d.next()}catch(a){a instanceof TypeError&&h(new O("nbunch is not a node or a sequence of nodes")),h(a)}};a=c}else a=Xa(this.adj);return a};W.prototype.nbunch_iter=W.prototype.b;function X(a,b){if(!(this instanceof X))return new X(a,b);this.graph={};this.node={};this.adj={};this.pred={};this.succ=this.adj;a!=l&&Oa(a,this);M(this.graph,b||{});this.edge=this.adj}w("jsnx.classes.DiGraph",X);w("jsnx.DiGraph",X);ia(X,W);X.__name__="DiGraph";X.prototype.F=function(a,b){b!=l||(b={});"object"!==q(b)&&h(new O("The attr_dict argument must be an object."));a in this.succ?M(this.node[a],b):(this.succ[a]={},this.pred[a]={},this.node[a]=b)};X.prototype.add_node=X.prototype.F;
X.prototype.i=function(a,b){var c,d,e,f,g;b=b||{};P(Xa(a),function(a){c=!(a in this.succ);ea(a)?(d=a[0],e=a[1],d in this.succ?(g=this.node[d],M(g,b,e)):(this.succ[d]={},this.pred[d]={},f=Ea(b),M(f,e),this.node[d]=f)):c?(this.succ[a]={},this.pred[a]={},this.node[a]=Ea(b)):M(this.node[a],b)},this)};X.prototype.add_nodes_from=X.prototype.i;
X.prototype.N=function(a){a in this.node||h(new O("The node "+a+" is not in the graph"));var b=this.succ[a];K(this.node,a);G(b,function(b,d){K(this.pred[d],a)},this);K(this.succ,a);G(this.pred[a],function(b,d){K(this.succ[d],a)},this);K(this.pred,a)};X.prototype.remove_node=X.prototype.N;
X.prototype.U=function(a){var b;P(a,function(a){a in this.succ&&(b=this.succ[a],K(this.node,a),G(b,function(b,e){K(this.pred[e],a)},this),K(this.succ,a),G(this.pred[a],function(b,e){K(this.succ[e],a)},this),K(this.pred,a))},this)};X.prototype.remove_nodes_from=X.prototype.U;
X.prototype.h=function(a,b,c){c=c||{};"object"!==q(c)&&h(new O("The attr_dict argument must be an object."));a in this.succ||(this.succ[a]={},this.pred[a]={},this.node[a]={});b in this.succ||(this.succ[b]={},this.pred[b]={},this.node[b]={});var d=L(this.adj[a],b,{});M(d,c);this.succ[a][b]=d;this.pred[b][a]=d};X.prototype.add_edge=X.prototype.h;
X.prototype.a=function(a,b){b=b||{};"object"!==q(b)&&h(new O("The attr_dict argument must be an object."));P(a,function(a){var d=Za(a),e,f,g;3===d?(e=a[0],f=a[1],g=a[2]):2===d?(e=a[0],f=a[1],g={}):h(new O("Edge tuple "+a.toString()+" must be a 2-tuple or 3-tuple."));e in this.succ||(this.succ[e]={},this.pred[e]={},this.node[e]={});f in this.succ||(this.succ[f]={},this.pred[f]={},this.node[f]={});a=L(this.adj[e],f,{});M(a,b,g);this.succ[e][f]=a;this.pred[f][e]=a},this)};
X.prototype.add_edges_from=X.prototype.a;X.prototype.s=function(a,b){try{K(this.succ[a],b),K(this.pred[b],a)}catch(c){c instanceof TypeError&&h(new O("The edge "+a+"-"+b+" is not in the graph")),h(c)}};X.prototype.remove_edge=X.prototype.s;X.prototype.A=function(a){P(a,function(a){var c=a[0];a=a[1];c in this.succ&&a in this.succ[c]&&(K(this.succ[c],a),K(this.pred[a],c))},this)};X.prototype.remove_edges_from=X.prototype.A;X.prototype.ta=function(a,b){return a in this.succ&&b in this.succ[a]};
X.prototype.has_successor=X.prototype.ta;X.prototype.sa=function(a,b){return a in this.pred&&b in this.pred[a]};X.prototype.has_predecessor=X.prototype.sa;X.prototype.ga=function(a){a in this.succ||h(new O("The node "+a+" is not in the digraph."));return Xa(this.succ[a])};X.prototype.successors_iter=X.prototype.ga;X.prototype.za=function(a){a in this.pred||h(new O("The node "+a+" is not in the digraph."));return Xa(this.pred[a])};X.prototype.predecessors_iter=X.prototype.za;
X.prototype.ba=function(a){a in this.succ||h(new O("The node "+a+" is not in the digraph."));return R(this.succ[a])};X.prototype.successors=X.prototype.ba;X.prototype.ya=function(a){a in this.succ||h(new O("The node "+a+" is not in the digraph."));return R(this.pred[a])};X.prototype.predecessors=X.prototype.ya;X.prototype.C=X.prototype.ba;X.prototype.neighbors=X.prototype.C;X.prototype.Y=X.prototype.ga;X.prototype.neighbors_iter=X.prototype.Y;
X.prototype.j=function(a,b){v(a)&&(b=a,a=l);var c,d,e;c=a!=l?Q(this.b(a),function(a){return[a,this.adj[a]]},this):eb(this.adj);return b?S(c,function(a){d=a[0];e=a[1];return T(e)},function(a){return[d,a[0],a[1]]}):S(c,function(a){d=a[0];e=a[1];return T(e)},function(a){return[d,a[0]]})};X.prototype.edges_iter=X.prototype.j;X.prototype.T=X.prototype.j;X.prototype.out_edges_iter=X.prototype.T;X.prototype.$=W.prototype.p;X.prototype.out_edges=X.prototype.$;
X.prototype.I=function(a,b){v(a)&&(b=a,a=l);var c,d;c=a!=l?Q(this.b(a),function(a){return[a,this.pred[a]]},this):eb(this.pred);return b?S(c,function(a){d=a[0];return T(a[1])},function(a){return[a[0],d,a[1]]}):S(c,function(a){d=a[0];return T(a[1])},function(a){return[a[0],d]})};X.prototype.in_edges_iter=X.prototype.I;X.prototype.H=function(a,b){return R(this.I(a,b))};X.prototype.in_edges=X.prototype.H;
X.prototype.m=function(a,b){var c;c=a!=l?ab(Q(this.b(a),function(a){return[a,this.succ[a]]},this),Q(this.b(a),function(a){return[a,this.pred[a]]},this)):ab(T(this.succ),T(this.pred));return b?Q(c,function(a){var c=a[0][1],f=a[1][1],g=0,j;for(j in c)g+=+L(c[j],b,1);for(j in f)g+=+L(f[j],b,1);return[a[0][0],g]}):Q(c,function(a){return[a[0][0],Za(a[0][1])+Za(a[1][1])]})};X.prototype.degree_iter=X.prototype.m;
X.prototype.G=function(a,b){var c;c=a!=l?Q(this.b(a),function(a){return[a,this.pred[a]]},this):T(this.pred);return b?Q(c,function(a){var c=0,f=a[1],g;for(g in f)c+=+L(f[g],b,1);return[a[0],c]}):Q(c,function(a){return[a[0],H(a[1])]})};X.prototype.in_degree_iter=X.prototype.G;X.prototype.M=function(a,b){var c;c=a!=l?Q(this.b(a),function(a){return[a,this.succ[a]]},this):T(this.succ);return b?Q(c,function(a){var c=0,f=a[1],g;for(g in f)c+=+L(f[g],b,1);return[a[0],c]}):Q(c,function(a){return[a[0],H(a[1])]})};
X.prototype.out_degree_iter=X.prototype.M;X.prototype.da=function(a,b){return this.q(a)?this.G(a,b).next()[1]:Wa(this.G(a,b))};X.prototype.in_degree=X.prototype.da;X.prototype.fa=function(a,b){return this.q(a)?this.M(a,b).next()[1]:Wa(this.M(a,b))};X.prototype.out_degree=X.prototype.fa;X.prototype.clear=function(){Da(this.succ);Da(this.pred);Da(this.node);Da(this.graph)};X.prototype.clear=X.prototype.clear;X.prototype.f=ba(n);X.prototype.is_multigraph=X.prototype.f;X.prototype.d=ba(k);
X.prototype.is_directed=X.prototype.d;X.prototype.B=function(){return fb(this)};X.prototype.to_directed=X.prototype.B;X.prototype.P=function(a){var b=new W;b.name(this.name());b.i(this);var c=this.pred,d;a?b.a(S(this.o(),function(a){d=a[0];return T(a[1])},function(a){if(a[0]in c[d])return[d,a[0],U(a[1])]})):b.a(S(this.o(),function(a){d=a[0];return T(a[1])},function(a){return[d,a[0],U(a[1])]}));b.graph=U(this.graph);b.node=U(this.node);return b};X.prototype.to_undirected=X.prototype.P;
X.prototype.reverse=function(a){(a=!r(a)||a)?(a=new this.constructor(l,{name:"Reverse of ("+this.name()+")"}),a.i(this),a.a(Q(this.j(k),function(a){return[a[1],a[0],U(a[2])]})),a.graph=U(this.graph),a.node=U(this.node)):(a=this.succ,this.succ=this.pred,this.pred=a,this.adj=this.succ,a=this);return a};X.prototype.reverse=X.prototype.reverse;
X.prototype.r=function(a){a=this.b(a);var b=new this.constructor,c=b.succ,d=b.pred,e=this.succ;P(a,function(a){c[a]={};d[a]={}});P(c,function(a){var b=c[a];G(e[a],function(e,m){m in c&&(b[m]=e,d[m][a]=e)})});P(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};X.prototype.subgraph=X.prototype.r;function Y(a,b){if(!(this instanceof Y))return new Y(a,b);W.call(this,a,b)}ia(Y,W);w("jsnx.classes.MultiGraph",Y);w("jsnx.MultiGraph",Y);Y.__name__="MultiGraph";
Y.prototype.h=function(a,b,c,d){var e,f;c!=l&&(!u(c)&&"number"!=typeof c)&&(d=c,c=l);d=d||{};"object"!==q(d)&&h(new O("The attr_dict argument must be an object."));a in this.adj||(this.adj[a]={},this.node[a]={});b in this.adj||(this.adj[b]={},this.node[b]={});if(b in this.adj[a]){f=this.adj[a][b];if(c==l)for(c=H(f);c in f;)c+=1;e=L(f,c,{});M(e,d);f[c]=e}else c!=l||(c=0),e={},M(e,d),f=Ga(c,e),this.adj[a][b]=f,this.adj[b][a]=f};Y.prototype.add_edge=Y.prototype.h;
Y.prototype.a=function(a,b){b=b||{};"object"!==q(b)&&h(new O("The attr_dict argument must be an object."));P(a,function(a){var d=Za(a),e,f,g=l,j={};4===d?(e=a[0],f=a[1],g=a[2],j=a[3]):3===d?(e=a[0],f=a[1],j=a[2]):2===d?(e=a[0],f=a[1]):h(new O("Edge tuple "+gb(a)+" must be a 2-tuple, 3-tuple or 4-tuple."));a=e in this.adj?L(this.adj[e],f,{}):{};if(g==l)for(g=H(a);g in a;)g+=1;a=L(a,g,{});M(a,b,j);this.h(e,f,g,a)},this)};Y.prototype.add_edges_from=Y.prototype.a;
Y.prototype.s=function(a,b,c){(!(a in this.adj)||!(b in this.adj[a]))&&h(new O("The edge "+a+"-"+b+" is not in the graph"));var d=this.adj[a][b];c!=l?(c in d||h(new O("The edge "+a+"-"+b+" with key "+c+" is not in the graph")),K(d,c)):K(d,Ca(d));0===H(d)&&(K(this.adj[a],b),a!=b&&K(this.adj[b],a))};Y.prototype.remove_edge=Y.prototype.s;Y.prototype.A=function(a){P(a,function(a){try{this.s(a[0],a[1],a[2])}catch(c){c instanceof O||h(c)}},this)};Y.prototype.remove_edges_from=Y.prototype.A;
Y.prototype.S=function(a,b,c){return c!=l?a in this.adj&&b in this.adj[a]&&c in this.adj[a][b]:a in this.adj&&b in this.adj[a]};Y.prototype.has_edge=Y.prototype.S;Y.prototype.p=function(a,b,c){return va(this.j(a,b,c))};Y.prototype.edges=Y.prototype.p;
Y.prototype.j=function(a,b,c){v(a)&&(v(b)&&(c=b),b=a,a=l);var d={},e,f;a=a!=l?Q(this.b(a),function(a){return[a,this.adj[a]]},this):T(this.adj);return b?S(a,function(a){e=a[0];var b=new C,c=T(a[1]);b.next=function(){try{return c.next()}catch(a){a===B&&(d[e]=1),h(a)}};return b},function(a){f=a[0];if(!(f in d))return T(a[1])},function(a){return c?[e,f,a[0],a[1]]:[e,f,a[1]]}):S(a,function(a){e=a[0];var b=new C,c=T(a[1]);b.next=function(){try{return c.next()}catch(a){a===B&&(d[e]=1),h(a)}};return b},function(a){f=
a[0];if(!(f in d))return T(a[1])},function(a){return c?[e,f,a[0]]:[e,f]})};Y.prototype.edges_iter=Y.prototype.j;Y.prototype.X=function(a,b,c,d){r(d)||(d=l);return a in this.adj&&b in this.adj[a]?c!=l?L(this.adj[a][b],c,d):this.adj[a][b]:d};Y.prototype.get_edge_data=Y.prototype.X;
Y.prototype.m=function(a,b){var c;c=a!=l?Q(this.b(a),function(a){return[a,this.adj[a]]},this):T(this.adj);return b!=l?F(c,function(a){var c=a[0];a=a[1];var f=0;G(a,function(a){G(a,function(a){f+=L(a,b,1)})});c in a&&G(a[c],function(a){f+=L(a,b,1)});return[c,f]}):F(c,function(a){var b=a[0];a=a[1];var c=0;G(a,function(a){c+=H(a)});return[b,c+ +(b in a&&H(a[b]))]})};Y.prototype.degree_iter=Y.prototype.m;Y.prototype.f=ba(k);Y.prototype.is_multigraph=Y.prototype.f;Y.prototype.d=ba(n);
Y.prototype.is_directed=Y.prototype.d;Y.prototype.B=function(){var a=new $;a.i(this);a.a(function(){var a,c;return S(this.o(),function(c){a=c[0];return T(c[1])},function(a){c=a[0];return T(a[1])},function(d){return[a,c,d[0],U(d[1])]})}.call(this));a.graph=U(this.graph);a.node=U(this.node);return a};Y.prototype.to_directed=Y.prototype.B;
Y.prototype.O=function(a,b){var c=[];a?b?G(this.adj,function(a,b){b in a&&G(a[b],function(a,d){c.push([b,b,d,a])})}):G(this.adj,function(a,b){b in a&&G(a[b],function(a){c.push([b,b,a])})}):b?G(this.adj,function(a,b){b in a&&G(a[b],function(a,d){c.push([b,b,d])})}):G(this.adj,function(a,b){b in a&&G(a[b],function(){c.push([b,b])})});return c};Y.prototype.selfloop_edges=Y.prototype.O;Y.prototype.D=function(a,b){return a==l?this.size():a in this.adj&&b in this.adj[a]?H(this.adj[a][b]):0};
Y.prototype.number_of_edges=Y.prototype.D;Y.prototype.r=function(a){a=this.b(a);var b=new this.constructor,c=b.adj,d=this.adj;E(a,function(a){var b={};c[a]=b;G(d[a],function(d,j){if(j in c){var m=Ea(d);b[j]=m;c[j][a]=m}})});G(this.node,function(a,c){b.node[c]=a});b.graph=this.graph;return b};Y.prototype.subgraph=Y.prototype.r;function $(a,b){if(!(this instanceof $))return new $(a,b);X.call(this,a,b)}ia($,X);var mb=$.prototype,nb=Y.prototype,ob;for(ob in nb)nb.hasOwnProperty(ob)&&"constructor"!==ob&&(mb[ob]=nb[ob]);w("jsnx.classes.MultiDiGraph",$);w("jsnx.MultiDiGraph",$);$.__name__="MultiDiGraph";
$.prototype.h=function(a,b,c,d){var e,f;c!=l&&(!u(c)&&"number"!=typeof c)&&(d=c,c=l);d=d||{};"object"!==q(d)&&h(new O("The attr_dict argument must be an object."));a in this.succ||(this.succ[a]={},this.pred[a]={},this.node[a]={});b in this.succ||(this.succ[b]={},this.pred[b]={},this.node[b]={});if(b in this.succ[a]){f=this.adj[a][b];if(c==l)for(c=H(f);c in f;)c+=1;e=L(f,c,{});M(e,d);f[c]=e}else c!=l||(c=0),e={},M(e,d),f=Ga(c,e),this.succ[a][b]=f,this.pred[b][a]=f};$.prototype.add_edge=$.prototype.h;
$.prototype.s=function(a,b,c){(!(a in this.adj)||!(b in this.adj[a]))&&h(new O("The edge "+a+"-"+b+" is not in the graph"));var d=this.adj[a][b];c!=l?(c in d||h(new O("The edge "+a+"-"+b+" with key "+c+" is not in the graph")),K(d,c)):K(d,Ca(d));0===H(d)&&(K(this.succ[a],b),K(this.pred[b],a))};$.prototype.remove_edge=$.prototype.s;
$.prototype.j=function(a,b,c){v(a)&&(v(b)&&(c=b),b=a,a=l);var d,e;a=a!=l?Q(this.b(a),function(a){return[a,this.adj[a]]},this):eb(this.adj);return b?S(a,function(a){d=a[0];return T(a[1])},function(a){e=a[0];return T(a[1])},function(a){return c?[d,e,a[0],a[1]]:[d,e,a[1]]}):S(a,function(a){d=a[0];return T(a[1])},function(a){e=a[0];return T(a[1])},function(a){return c?[d,e,a[0]]:[d,e]})};$.prototype.edges_iter=$.prototype.j;$.prototype.T=$.prototype.j;$.prototype.out_edges_iter=$.prototype.T;
$.prototype.$=function(a,b,c){return va(this.T(a,b,c))};$.prototype.out_edges=$.prototype.$;$.prototype.I=function(a,b,c){v(a)&&(b=a,a=l);var d,e;a=da?Q(this.b(a),function(a){return[a,this.pred[a]]},this):eb(this.pred);return b?S(a,function(a){d=a[0];return T(a[1])},function(a){e=a[0];return T(a[1])},function(a){return c?[e,d,a[0],a[1]]:[e,d,a[1]]}):S(a,function(a){d=a[0];return T(a[1])},function(a){e=a[0];return T(a[1])},function(a){return c?[e,d,a[0]]:[e,d]})};$.prototype.in_edges_iter=$.prototype.I;
$.prototype.H=function(a,b,c){return va(this.I(a,b,c))};$.prototype.in_edges=$.prototype.H;
$.prototype.m=function(a,b){var c;c=a!=l?ab(F(this.b(a),function(a){return[a,this.succ[a]]},this),F(this.b(a),function(a){return[a,this.pred[a]]},this)):ab(T(this.succ),T(this.pred));return b!=l?Q(c,function(a){var c=a[0][1],f=0;G(a[1][1],function(a){G(a,function(a){f+=+L(a,b,1)})});G(c,function(a){G(a,function(a){f+=+L(a,b,1)})});return[a[0][0],f]}):Q(c,function(a){var b=0,c=0;G(a[1][1],function(a){b+=Za(a)});G(a[0][1],function(a){c+=Za(a)});return[a[0][0],b+c]})};$.prototype.degree_iter=$.prototype.m;
$.prototype.G=function(a,b){var c;c=a!=l?Q(this.b(a),function(a){return[a,this.pred[a]]},this):T(this.pred);return b!=l?Q(c,function(a){var c=0;G(a[1],function(a){G(a,function(a){c+=+L(a,b,1)})});return[a[0][0],c]}):Q(c,function(a){var b=0;G(a[1],function(a){b+=H(a)});return[a[0],b]})};$.prototype.in_degree_iter=$.prototype.G;
$.prototype.M=function(a,b){var c;c=a!=l?Q(this.b(a),function(a){return[a,this.succ[a]]},this):T(this.succ);return b!=l?Q(c,function(a){var c=0;G(a[1],function(a){G(a,function(a){c+=+L(a,b,1)})});return[a[0][0],c]}):Q(c,function(a){var b=0;G(a[1],function(a){b+=H(a)});return[a[0],b]})};$.prototype.out_degree_iter=$.prototype.M;$.prototype.f=ba(k);$.prototype.is_multigraph=$.prototype.f;$.prototype.d=ba(k);$.prototype.is_directed=$.prototype.d;$.prototype.B=function(){return fb(this)};
$.prototype.to_directed=$.prototype.B;$.prototype.P=function(a){var b=new Y;b.name(this.name());b.i(this);var c=this,d,e;a?b.a(S(this.o(),function(a){d=a[0];return T(a[1])},function(a){e=a[0];return T(a[1])},function(a){if(c.S(e,d,a[0]))return[d,e,a[0],U(a[1])]})):b.a(S(this.o(),function(a){d=a[0];return T(a[1])},function(a){e=a[0];return T(a[1])},function(a){return[d,e,a[0],U(a[1])]}));b.graph=U(this.graph);b.node=U(this.node);return b};$.prototype.to_undirected=$.prototype.P;
$.prototype.r=function(a){a=this.b(a);var b=new this.constructor,c=b.succ,d=b.pred,e=this.succ;E(a,function(a){c[a]={};d[a]={}});P(c,function(a){var b=c[a];G(e[a],function(e,m){if(m in c){var y=Ea(e);b[m]=y;d[m][a]=y}})});P(b,function(a){b.node[a]=this.node[a]},this);b.graph=this.graph;return b};$.prototype.subgraph=$.prototype.r;
$.prototype.reverse=function(a){(a=!r(a)||a)?(a=new this.constructor(l,{name:"Reverse of ("+this.name()+")"}),a.i(this),a.a(F(this.j(k,k),function(a){return[a[1],a[0],a[2],U(a[3])]})),a.graph=U(this.graph),a.node=U(this.node)):(a=this.succ,this.succ=this.pred,this.pred=a,this.adj=this.succ,a=this);return a};$.prototype.reverse=$.prototype.reverse;w("jsnx.nodes",function(a){return a.z()});w("jsnx.nodes_iter",function(a){return a.K()});w("jsnx.edges",function(a,b){return a.p(b)});w("jsnx.edges_iter",function(a,b){return a.j(b)});w("jsnx.degree",function(a,b,c){return a.l(b,c)});w("jsnx.neighbors",function(a,b){return a.C(b)});w("jsnx.number_of_nodes",function(a){return a.L()});w("jsnx.number_of_edges",function(a){return a.D()});w("jsnx.density",function(a){var b=a.L(),c=a.D();return 0===c?0:a.d()?c/(b*(b-1)):2*c/(b*(b-1))});
w("jsnx.degree_histogram",function(a){a=I(a.l());for(var b=Math.max.apply(Math,a)+1,c=[],d=0;d<b;d++)c[d]=0;ka(a,function(a){c[a]+=1});return c});w("jsnx.is_directed",function(a){return a.d()});w("jsnx.freeze",function(a){function b(){h(new O("Frozen graph can't be modified"))}a.F=b;a.i=b;a.N=b;a.U=b;a.h=b;a.a=b;a.s=b;a.A=b;a.clear=b;a.qa=k;return a});w("jsnx.is_frozen",function(a){return!!a.qa});w("jsnx.subgraph",function(a,b){return a.r(b)});
w("jsnx.create_empty_copy",function(a,b){r(b)||(b=k);var c=new a.constructor;b&&c.i(a);return c});
w("jsnx.info",function(a,b){var c="";if(b!=l)a.q(b)||h(new O("node "+b+" not in graph")),c=c+("Node "+b+" has the following properties:\n")+("Degree: "+a.l(b)+"\n"),c+="Neighbors: "+a.C(b).join(" ");else{var c=c+("Name: "+a.name()+"\n"),c=c+("Type: "+a.constructor.__name__+"\n"),c=c+("Number of nodes: "+a.L()+"\n"),c=c+("Number of edges: "+a.D()+"\n"),d=a.L();if(0<d)if(a.d())c+="Average in degree: "+(V.n.apply(l,I(a.da()))/d).toFixed(4)+"\n",c+="Average out degree: "+(V.n.apply(l,I(a.fa()))/d).toFixed(4);
else var e=V.n.apply(l,I(a.l())),c=c+("Average degree: "+(e/d).toFixed(4))}return c});w("jsnx.set_node_attributes",function(a,b,c){G(c,function(c,e){a.Z[e][b]=c})});function pb(a,b){var c={};G(a.Z,function(a,e){b in a&&(c[e]=a[b])});return c}w("jsnx.get_node_attributes",pb);w("jsnx.set_edge_attributes",function(a,b,c){G(c,function(b,c){c=c.split(",");a.k(c[0])[c[1]]=b})});pb=function(a,b){var c={};G(a.p(k),function(a){b in a[2]&&(c[[a[0],a[1]]]=a[2][b])});return c};w("jsnx.get_edge_attributes",{}.Ka);var rb={};function sb(a,b){a.d()&&h(new O("triangles() is not defined for directed graphs."));if(a.q(b))return Math.floor(tb(a,b).next()[2]/2);var c={};E(tb(a,b),function(a){c[a[0]]=Math.floor(a[2]/2)});return c}w("jsnx.triangles",sb);
function tb(a,b){a.f()&&h(new O("Not defined for multigraphs."));var c;c=b!=l?S(a.b(b),function(b){return[b,a.k(b)]}):T(a.adj);return F(c,function(b){var c=new N(J(b[1])),f=0;c.remove(b[0]);E(c,function(b){var d=new N(J(a.k(b)));d.remove(b);f+=La(c,d).c()});return[b[0],c.c(),f]})}
w("jsnx.average_clustering",function(a,b,c,d){2===arguments.length?u(b)?(c=b,b=l):v(b)&&(d=b,b=l):3===arguments.length&&v(c)&&(d=c,c=l);c!=l||(c=l);d!=l||(d=k);var e=I(ub(a,b,c));d||(e=la(e,function(a){return 0<a}));return V.n.apply(V,e)/e.length});
function ub(a,b,c){a.d()&&h(new O("Clustering algorithms are not defined for directed graphs."));if(c!=l){var d=c;a.f()&&h(new O("Not defined for multigraphs."));r(d)||(d="weight");var e;if(0===a.p().length)c=1;else{c=a.p(k);var f=function(a){return L(a[2],d,1)};c="function"==q(f)?Q(c,function(){return f.apply(l,arguments)}):R(c);c=Math.max.apply(l,c)}e=c;c=b!=l?S(a.b(b),function(b){return[b,a.k(b)]}):T(a.adj);c=F(c,function(b){var c=b[0],f=new N(J(b[1]));f.remove(c);var g=0,t=new N;E(f,function(b){var j=
L(a.k(c)[b],d,1)/e;t.add(b);var Z=Ma(new N(J(a.k(b))),t);E(La(f,Z),function(f){var y=L(a.k(b)[f],d,1)/e;f=L(a.k(c)[f],d,1)/e;g+=Math.pow(j*y*f,1/3)})});return[c,f.c(),2*g]})}else c=tb(a,b);var g={};E(c,function(a){g[a[0]]=0===a[2]?0:a[2]/(a[1]*(a[1]-1))});return a.q(b)?I(g)[0]:g}w("jsnx.clustering",ub);w("jsnx.transitivity",function(a){var b=0,c=0;E(tb(a),function(a){c+=a[1]*(a[1]-1);b+=a[2]});return 0===b?0:b/c});
w("jsnx.square_clustering",function(a,b){var c=b==l?a:a.b(b),d={};E(c,function(b){var c=d[b]=0;E(cb(J(a.k(b))),function(g){var j=g[0];g=g[1];var m=La(new N(J(a.k(j))),J(a.k(g)));m.remove(b);m=m.c();d[b]+=m;var y=m+1,x=a.k(j);g in x&&(y+=1);c+=(H(a.k(j))-y)*(H(a.k(g))-y)+m});0<c&&(d[b]/=c)});return a.q(b)?I(d)[0]:d});function vb(a){var b=-1,c={},d=new N;E(a.o(),function(a){var e=new N(J(a[1]));e.remove(a[0]);var f=e.c();f>b?(c[a[0]]=d=e,b=f):c[a[0]]=e});var e=new N(J(c)),f=Ma(e,d),g=new N,j=[],m=[];a=new C;a.next=function(){0===f.c()&&0===j.length&&h(B);var a,x;if(0<f.c())a=wa(f),f.remove(a);else{var t=j.pop();e=t[0];g=t[1];f=t[2];m.pop();return this.next()}m.push(a);e.remove(a);g.add(a);var D=c[a],t=La(e,D),D=La(g,D);if(0===t.c()&&(0===D.c()&&(x=oa(m)),m.pop(),x))return x;if(0===D.c()&&1===t.c())return x=na(m,
t.w()),m.pop(),x;var ma=t.c(),Z=-1,qb,za;for(x=ua(D);(a=wa(x,l))!==l&&!(a=La(t,c[a]),za=a.c(),za>Z&&(qb=a,Z=za,Z===ma)););if(Z===ma)return m.pop(),this.next();b=-1;for(x=ua(t);(a=wa(x,l))!==l&&!(a=La(t,c[a]),za=a.c(),za>b&&(d=a,b=za,b===ma-1)););Z>b&&(d=qb);j.push([e,g,f]);e=t;g=D;f=Ma(e,d);return this.next()};return a}w("jsnx.find_cliques",vb);
w("jsnx.find_cliques_recursive",function(a){var b={};E(a.o(),function(a){var c=new N(J(a[1]));c.remove(a[0]);b[a[0]]=c});a:{for(var c in b){a=n;break a}a=k}if(a)return[];a=new N(J(b));c=new N;var d=[];wb(b,a,c,[],d);return d});
function wb(a,b,c,d,e){var f=-1,g=b.c(),j,m,y,x;for(m=ua(c);(y=wa(m,l))!==l;)if(y=La(b,a[y]),x=y.c(),x>f&&(j=y,f=x,x===g))return;E(b,function(c){c=La(b,a[c]);var d=c.c();d>f&&(j=c,f=d)});g=Ma(b,j);E(g,function(f){b.remove(f);d.push(f);var g=a[f];f=La(b,g);g=La(c,g);f.J()&&g.J()?e.push(oa(d)):g.J()&&1===f.c()?e.push(na(d,f.w())):wb(a,f,g,d,e);c.add(d.pop())})}w("jsnx.graph_clique_number",function(a,b){b!=l||(b=vb(a));var c=0;P(b,function(a){c=a.length>c?a.length:c});return c});
w("jsnx.graph_number_of_cliques",function(a,b){b!=l||(b=vb(a));return R(b).length});function xb(a,b,c){c!=l||(c=va(vb(a)));b!=l||(b=a.z());var d;if(ea(b))d={},ka(b,function(a){d[a]=la(c,function(b){return 0<=ja(b,a)||0<=ja(b,a+"")}).length});else{var e=b;d=la(c,function(a){return 0<=ja(a,e)||0<=ja(a,e+"")}).length}return d}w("jsnx.number_of_cliques",xb);function yb(a,b){if(a.v()!=b.v())return n;var c=a.l(),d=sb(a),e=xb(a),f=[],g;for(g in c)f.push([c[g],d[g],e[g]]);f.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]!==b[1]?a[1]-b[1]:a[2]-b[2]});var c=b.l(),d=sb(b),e=xb(b),j=[];for(g in c)j.push([c[g],d[g],e[g]]);j.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]!==b[1]?a[1]-b[1]:a[2]-b[2]});return!qa(f,j,function(a,b){return qa(a,b)})?n:k}w("jsnx.algorithms.isomorphism.could_be_isomorphic",yb);w("jsnx.could_be_isomorphic",yb);
function zb(a,b){if(a.v()!=b.v())return n;var c=a.l(),d=sb(a),e=[],f;for(f in c)e.push([c[f],d[f]]);e.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]-b[1]});var c=b.l(),d=sb(b),g=[];for(f in c)g.push([c[f],d[f]]);g.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:a[1]-b[1]});return!qa(e,g,function(a,b){return qa(a,b)})?n:k}w("jsnx.algorithms.isomorphism.fast_could_be_isomorphic",zb);w("jsnx.fast_could_be_isomorphic",zb);
function Ab(a,b){if(a.v()!=b.v())return n;var c=I(a.l());c.sort();var d=I(b.l());d.sort();return!qa(c,d)?n:k}w("jsnx.algorithms.isomorphism.faster_could_be_isomorphic",Ab);w("jsnx.faster_could_be_isomorphic",Ab);function Bb(a,b){if("eg"===b)return Cb(a);if(b==l||"hh"===b)return Db(a);h(new Qa("`opt_method` must be 'eg' or 'hh'"))}w("jsnx.is_valid_degree_sequence",Bb);function Db(a){if(0===a.length)return k;if(!Aa(a)||0>Math.min.apply(l,a)||0!==V.n.apply(l,a)%2)return n;for(a=oa(a);0<a.length;){z.sort.call(a,sa);if(0>a[0])break;var b=a.pop();if(0===b)return k;if(b>a.length)break;for(var c=a.length-1,b=a.length-(b+1);c>b;c--)a[c]-=1}return n}w("jsnx.is_valid_degree_sequence_havel_hakimi",Db);
function Cb(a){if(0===a.length)return k;if(!Aa(a)||0>Math.min.apply(l,a)||0!==V.n.apply(l,a)%2)return n;var b=a.length,c=oa(a).sort(function(a,b){return b-a}),d=[],e;e=1;for(a=c.length;e<a;e++)c[e]<c[e-1]&&d.push(e);var f,g;e=0;for(a=d.length;e<a;e++)if(f=V.n.apply(l,c.slice(0,d[e])),g=d[e]*(d[e]-1)+V.n.apply(l,va(F(bb(d[e],b),function(a){return Math.min(d[e],c[a])}))),f>g)return n;return k}w("jsnx.is_valid_degree_sequence_erdos_gallai",Cb);function Eb(a){var b={},c={},d=new N,e=[],f=[],g=0,j=n;E(a.K(),function(m){var y,x,t,D;if(!d.contains(m))for(D=[m];0<D.length;){m=D[D.length-1];m in b||(g+=1,b[m]=g);j=k;y=a.C(m);for(t=0;t<y.length;t++)if(x=y[t],!(x in b)){D.push(x);j=n;break}if(j){c[m]=b[m];for(t=0;t<y.length;t++)x=y[t],d.contains(x)||(c[m]=b[x]>b[m]?Math.min(c[m],c[x]):Math.min(c[m],b[x]));D.pop();if(c[m]===b[m]){d.add(m);for(y=[m];0<e.length&&b[e[e.length-1]]>b[m];)x=e.pop(),d.add(x),y.push(x);f.push(y)}else e.push(m)}}});f.sort(function(a,
b){return b.length-a.length});return f}w("jsnx.strongly_connected_components",Eb);w("jsnx.simple_cycles",function(a){function b(a){function g(a){var b;for(e.remove(a);0<d[a].length;)b=d[a].pop(),e.contains(b)&&g(b)}var j=n,m,D,t=c.ba(a);y.push(a);e.add(a);for(m=0;m<t.length;m++)D=t[m],D===f?(j=y.slice(0),j.push(f),x.push(j),j=k):e.contains(D)||b(D)&&(j=k);if(j)g(a);else for(m=0;m<t.length;m++)D=t[m],0<=ja(d[D],a)||d[D].push(a);a!==y.pop()&&console.log("DANGER WILL ROBINSON!");return j}a.d()||h(new O("simple_cycles() is not defined for undirected graphs."));var c,d={},e=new N,f,
g,j,m=a.z(),y=[],x=[],t,D,ma,Z={};for(j=0;j<m.length;j++)d[m[j]]=[],Z[m[j]]=j;for(g=0;g<m.length-1;)if(f=m[g],j=a.r(m.slice(g)),t=Eb(j),0===t.length)g=m.length;else{c=ma=D=aa;for(j=0;j<t.length;j++)for(g=0;g<t[j].length;g++)D===aa?(D=t[j][g],c=t[j],ma=Z[D]):Z[t[j][g]]<ma&&(D=t[j][g],c=t[j],ma=Z[D]);c=a.r(c);f=D;g=Z[D];t=c.z();for(j=0;j<t.length;j++)e.remove(t[j]),d[t[j]]=[];b(f);g++}return x});function Fb(a,b){var c=Gb(a,b);c.name("complete_graph("+a+")");1<a&&c.a(c.d()?db(bb(a)):cb(bb(a)));return c}w("jsnx.complete_graph",Fb);w("jsnx.cycle_graph",function(a,b){var c=Hb(a,b);c.name("cycle_graph("+a+")");1<a&&c.h(a-1,0);return c});function Gb(a,b){a instanceof W&&(b=a,a=l);a!=l||(a=0);var c;b!=l?(c=b,c.clear()):c=new W;c.i(bb(a));c.name("empty_graph("+a+")");return c}w("jsnx.empty_graph",Gb);w("jsnx.null_graph",function(a){a=Gb(0,a);a.name("null_graph()");return a});
function Hb(a,b){var c=Gb(a,b);c.name("path_graph("+a+")");c.a(F(bb(a-1),function(a){return[a,a+1]}));return c}w("jsnx.path_graph",Hb);w("jsnx.trivial_graph",function(a){a=Gb(1,a);a.name("null_graph()");return a});w("jsnx.fast_gnp_random_graph",function(a,b,c){c!=l||(c=n);var d=Gb(a);d.name("fast_gnp_random_graph("+a+","+b+")");if(0>=b||1<=b)return Ib(a,b,c);var e=1,f=-1;b=Math.log(1-b);if(c)for(d=X(d);e<a;){c=Math.log(1-Math.random());f=f+1+Math.floor(c/b);for(e===f&&(f+=1);f>=a&&e<a;)f-=a,e+=1,e==f&&(f+=1);e<a&&d.h(e,f)}else for(;e<a;){c=Math.log(1-Math.random());for(f=f+1+Math.floor(c/b);f>=e&&e<a;)f-=e,e+=1;e<a&&d.h(e,f)}return d});
function Ib(a,b,c){var d;d=c?X():W();d.i(bb(a));d.name("gnp_random_graph("+a+","+b+")");if(0>=b)return d;if(1<=b)return Fb(a,d);a=d.d()?db(bb(a)):cb(bb(a));E(a,function(a){Math.random()<b&&d.h(a[0],a[1])});return d}w("jsnx.gnp_random_graph",Ib);w("jsnx.binomial_graph",Ib);w("jsnx.erdos_renyi_graph",Ib);w("jsnx.havel_hakimi_graph",function(a,b){Bb(a)||h(new O("Invalid degree sequence"));b!=l&&(b.d()&&h(new O("Directed Graph not supported")),b.f()&&h(new O("Havel-Hakimi requires simple graph")));var c=a.length,d=Gb(c,b);if(0===c||0===Math.max.apply(l,a))return d;for(c=va(F(d,function(b){return[a[b],b]}));0<c.length;){c.sort(function(a,b){return a[0]!==b[0]?a[0]-b[0]:+a[1]-+b[1]});if(0>c[0][0])return n;var e=c.pop();if(0===e[0])break;if(e[0]>c.length)return n;for(var f=c.length,g=f-e[0];g<f;g++)d.h(e[1],
c[g][1]),c[g][0]-=1}d.name("havel_hakimi_graph "+d.v()+" nodes "+d.size()+" edges");return d});function Jb(a,b,c){var d=b;"function"==q(b)&&(d={},E(a.K(),function(a){d[a]=b(a)}));var e;if(!r(c)||c){var f=d,g=new a.constructor;g.name("("+a.name()+")");a.f()?g.a(F(a.j(k,k),function(a){return[L(f,a[0],a[0]),L(f,a[1],a[1]),a[2],Ea(a[3])]})):g.a(F(a.j(k),function(a){return[L(f,a[0],a[0]),L(f,a[1],a[1]),Ea(a[2])]}));g.i(F(a,function(a){return L(f,a,a)}));c={};for(e in a.node)c[L(f,e,e)]=Ea(a.node[e]);M(g.node,c);M(g.graph,Ea(a.graph));e=g}else{var j=d;e=new N(J(j));if(0<La(e,j).c()){e=X(eb(j));e.A(e.O());
try{g=rb.Ja.Xa(e)}catch(m){m instanceof Ta&&h(new Ta("The node label sets are overlapping and no ordering can resolve the mapping. Use copy=True."))}g.reverse()}else g=e;var y=a.f(),x=a.d(),t;E(g,function(b){var c;b in j&&(c=j[b],a.q(b)||h(new O("Node "+b+" is not in the graph.")),a.F(c,a.node[b]),y?(t=A(a.p(b,k,k),function(a){return[c,a[1],a[2],a[3]]}),x&&(t=na(t,A(a.H(b,k,k),function(a){return[a[0],c,a[2],a[3]]})))):(t=A(a.p(b,k),function(a){return[c,a[1],a[2]]}),x&&(t=na(t,A(a.H(b,k),function(a){return[a[0],
c,a[2]]})))),a.N(b),a.a(t))});e=a}return e}w("jsnx.relabel_nodes",Jb);
w("jsnx.convert_node_labels_to_integers",function(a,b,c,d){3===arguments.length&&v(c)?(d=c,c=l):2===arguments.length&&(v(b)?(d=b,b=l):u(b)&&(c=b,b=l));b!=l||(b=0);c!=l||(c="default");d!=l||(d=k);var e={},f,g,j,m;if("default"===c){f=a.z();g=0;j=b;for(m=f.length;g<m;g++,j++)e[f[g]]=j}else if("sorted"===c){f=a.z();f.sort();g=0;j=b;for(m=f.length;g<m;g++,j++)e[f[g]]=j}else if("increasing degree"===c){f=va(a.m());f.sort(function(a,b){return a[1]-b[1]});g=0;j=b;for(m=f.length;g<m;g++,j++)e[f[g][0]]=j}else if("decreasing degree"===
c){f=va(a.m());f.sort(function(a,b){return b[1]-a[1]});g=0;j=b;for(m=f.length;g<m;g++,j++)e[f[g][0]]=j}else h(new O("Unkown node ordering: "+c));g=Jb(a,e);g.name("("+a.name()+")_with_int_labels");d||(g.node_labels=e);return g});}());
